uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

curl-download-dog:
    curl --silent --fail --show-error --location --output data/dog.jpg https://i.ibb.co/bLvrvRV/shiba-inu-dog.jpg
