update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

curl-download-dog:
    curl --silent --fail --show-error --location --output data/dog.jpg https://i.ibb.co/bLvrvRV/shiba-inu-dog.jpg
