create:
    argocd app create production-hm-argo-cd --file=argo-cd-manifests/hm-argo-cd-application.yaml

update:
    argocd app create production-hm-argo-cd --file=argo-cd-manifests/hm-argo-cd-application.yaml --upsert

delete:
    argocd app delete production-hm-argo-cd --yes
