HELM_RELEASE_NAME := "cilium"
NAMESPACE := "kube-system"

show-version:
    cilium version --namespace={{ NAMESPACE }} --helm-release-name={{ HELM_RELEASE_NAME }}

show-status:
    cilium status --namespace={{ NAMESPACE }} --wait

show-encryption-status:
    kubectl --namespace={{ NAMESPACE }} exec -t daemonset/cilium -- cilium encrypt status

test-connectivity:
    cilium connectivity test --namespace={{ NAMESPACE }}
