show-version:
    cilium version --helm-release-name=cilium --namespace=kube-system

show-status:
    cilium status --wait --namespace=kube-system

show-encryption-status:
    kubectl --namespace=kube-system exec -i -t daemonset/cilium -- cilium encrypt status

test-connectivity:
    cilium connectivity test --namespace=kube-system
