cilium-version:
	cilium version --helm-release-name=hm-cilium --namespace=production-hm-cilium
cilium-status:
	cilium status --wait --namespace=production-hm-cilium
cilium-test:
	cilium connectivity test --namespace=production-hm-cilium
