argo-cd-app-create:
    argocd app create production-hm-mimir --file=argo-cd-manifests/hm-mimir-application.yaml

argo-cd-app-update:
    argocd app create production-hm-mimir --file=argo-cd-manifests/hm-mimir-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-mimir --yes
