update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev --config_path=configs/pi05_inference_config.json

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
