update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

publish-docker-image:
    docker build --platform=linux/amd64 --tag=harbor.hongbomiao.com/hm/parquet-visualizer:latest .
    docker push harbor.hongbomiao.com/hm/parquet-visualizer:latest
