uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

publish-development-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=ghcr.io/hongbo-miao/hm-prefect-greet:development . && \
    docker push ghcr.io/hongbo-miao/hm-prefect-greet:development

publish-production-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=ghcr.io/hongbo-miao/hm-prefect-greet:latest . && \
    docker push ghcr.io/hongbo-miao/hm-prefect-greet:latest

deploy-development:
    uv run poe deploy --environment=development

deploy-production:
    uv run poe deploy --environment=production

run-development:
    uv run poe run -- greet/hm-development-greet

run-production:
    uv run poe run -- greet/hm-production-greet
