[package]
name = "arrow-flight-sql-client"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "=1.0.104"
arrow = { version = "=59.0.0", features = ["prettyprint", "chrono-tz"] }
arrow-flight = { version = "=59.0.0", features = ["flight-sql"] }
futures-util = "=0.3.34"
tokio = { version = "=1.52.4", features = ["full"] }
tonic = "=0.14.6"
tracing = "=0.1.44"
tracing-subscriber = "=0.3.23"
