initialize:
    # vagrant init gusztavvargadr/windows-11
    vagrant init hbsmith/win11-arm

up:
    vagrant up --provider=parallels

suspend:
    vagrant suspend

halt:
    vagrant halt

destroy:
    vagrant destroy --force

ssh:
    vagrant ssh

status:
    vagrant status
