uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

train:
    uv run poe train

test:
    uv run poe test

test-story:
    uv run poe test -- --stories tests/test_stories.yml

visualize:
    uv run poe visualize

start-rasa-server:
    uv run poe start-rasa-server

start-action-server:
    uv run poe start-action-server

telemetry-disable:
    uv run poe telemetry-disable

shell:
    uv run poe shell

interactive:
    uv run poe interactive

# Docker
docker-build:
    cd ../.. && \
    docker build --file=machine-learning/hm-rasa/Dockerfile --tag=ghcr.io/hongbo-miao/hm-rasa-action-server:latest .

docker-push:
    docker push hongbomiao/hm-rasa-action-server:latest
