create:
    argocd app create production-hm-kafbat-ui --file=argo-cd-manifests/hm-kafbat-ui-application.yaml

update:
    argocd app create production-hm-kafbat-ui --file=argo-cd-manifests/hm-kafbat-ui-application.yaml --upsert

delete:
    argocd app delete production-hm-kafbat-ui --yes
