uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-download-model:
    uv run poe download-model

uv-run-launch-server:
    uv run poe launch-server

uv-run-dev:
    uv run poe dev

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage
