create:
    argocd app create production-hm-external-dns --file=argo-cd-manifests/hm-external-dns-application.yaml

update:
    argocd app create production-hm-external-dns --file=argo-cd-manifests/hm-external-dns-application.yaml --upsert

delete:
    argocd app delete production-hm-external-dns --yes
