sealed-secrets-seal:
    cat secrets/hm-label-studio-secret.unsealed.yaml | \
    kubeseal \
    	--controller-namespace=production-hm-sealed-secrets \
    	--controller-name=hm-sealed-secrets \
    	--format=yaml \
    	> kubernetes-manifests/hm-label-studio-secret.yaml

argo-cd-app-create:
    argocd app create production-hm-label-studio --file=argo-cd-manifests/hm-label-studio-application.yaml

argo-cd-app-update:
    argocd app create production-hm-label-studio --file=argo-cd-manifests/hm-label-studio-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-label-studio --yes
