sealed-secrets-seal-hm-prefect-worker-secret:
    cat secrets/hm-prefect-worker-secret.unsealed.yaml | \
    kubeseal \
        --cert=https://sealed-secrets.hongbomiao.com/v1/cert.pem \
        --format=yaml \
        > kubernetes-manifests/hm-prefect-worker-secret.yaml

sealed-secrets-seal-hm-harbor-secret:
    cat secrets/hm-harbor-secret.unsealed.yaml | \
    kubeseal \
        --cert=https://sealed-secrets.hongbomiao.com/v1/cert.pem \
        --format=yaml \
        > kubernetes-manifests/hm-harbor-secret.yaml
