port: 4222
http_port: 8222

jetstream {}

# Map "SENSOR_TELEMETRY_STREAMS.{publisher_id}" to "SENSOR_TELEMETRY_STREAMS.{publisher_id}.{partition_index}"
# partition(2,1): deterministically hash the 1st wildcard (publisher_id) into 2 partitions (0 or 1)
mappings = {
  "SENSOR_TELEMETRY_STREAMS.*": "SENSOR_TELEMETRY_STREAMS.{{wildcard(1)}}.{{partition(2,1)}}"
}
