update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

generate-dashboard:
    uv run poe generate-dashboard

upload-dashboard:
    uv run poe upload-dashboard
