uv-install-python:
	uv python install
uv-update-lock-file:
	uv lock
uv-install-dependencies:
	uv sync --dev

uv-run-test:
	uv run poe test
uv-run-test-coverage:
	uv run poe test-coverage

uv-run-generate-dashboard:
	uv run poe generate-dashboard
uv-run-upload-dashboard:
	uv run poe upload-dashboard
