kind-up:
    kind create cluster --config=kubernetes/kind/kind-cluster.yaml

kind-down:
    kind delete cluster --name=seatunnel

tilt-up *args:
    kubectl config use-context kind-seatunnel
    tilt up {{ args }}

tilt-down:
    tilt down --delete-namespaces

docker-compose-up:
    docker compose --file=docker-compose.development.yaml up --detach

docker-compose-stop:
    docker compose --file=docker-compose.development.yaml stop

docker-compose-down:
    docker compose --file=docker-compose.development.yaml down --volumes

docker-compose-restart:
    docker compose --file=docker-compose.development.yaml down --volumes
    docker compose --file=docker-compose.development.yaml up --detach --build
