update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

libmagic-install:
    brew install libmagic

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
