create:
    argocd app create production-hm-starrocks --file=argo-cd-manifests/hm-starrocks-application.yaml

update:
    argocd app create production-hm-starrocks --file=argo-cd-manifests/hm-starrocks-application.yaml --upsert

delete:
    argocd app delete production-hm-starrocks --yes
