openfoam-install:
    brew install gerlero/openfoam/openfoam

openfoam-run:
    openfoam

openfoam-generate-mesh:
    blockMesh

openfoam-solve-incompressible-laminar-navier-stokes-equations-using-piso-algorithm:
    icoFoam

openfoam-view:
    paraFoam
