update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

download-model:
    uv run poe download-model

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
