git-add:
	git add .
git-commit:
	git commit --message="xxx"

git-branch-show-head:
	cat .git/HEAD
git-branch-switch:
	git switch branch-name
git-branch-create-and-switch:
	git switch -c branch-name
git-branch-create-by-commit-hash:
	git branch branch-name xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
git-branch-list-local:
	git branch
git-branch-list-remote:
	git branch -r
git-fetch-branches:
	git fetch --all
git-pull-rebase:
	git pull --rebase

git-log:
	git log
git-status:
	git status
git-recover:
	git reflog --no-abbrev
	git branch branch-name xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Git LFS
git-lfs-install:
	git lfs install
git-lfs-track:
	git lfs track "*.mp4"
git-lfs-untrack:
	git lfs untrack "*.mp4"
git-lfs-status:
	git lfs status
git-lfs-list:
	git lfs ls-files

# Gitleaks
gitleaks-install:
	brew install gitleaks
gitleaks-detect:
	gitleaks detect --source=. --verbose
