create:
    argocd app create production-hm-vertical-pod-autoscaler --file=argo-cd-manifests/hm-vertical-pod-autoscaler-application.yaml

update:
    argocd app create production-hm-vertical-pod-autoscaler --file=argo-cd-manifests/hm-vertical-pod-autoscaler-application.yaml --upsert

delete:
    argocd app delete production-hm-vertical-pod-autoscaler --yes
