update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

upload-spark-scripts:
    cd ../.. && \
    aws s3 cp aws-glue/spark-scripts/src/ s3://hm-production-bucket/aws-glue/spark-scripts/ --recursive
