uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

xxhash-install:
    brew install xxhash

xxhash-xxh32:
    xxh32sum file.txt

xxhash-xxh64:
    xxh64sum file.txt

xxhash-xxh128:
    xxh128sum file.txt
