IOS_SIMULATOR := "platform=iOS Simulator,name=iPhone 17,OS=26.0"

build:
    xcodebuild build-for-testing \
        -project mobile-ios.xcodeproj \
        -scheme mobile-ios \
        -destination "{{ IOS_SIMULATOR }}"

test:
    xcodebuild test-without-building \
        -project mobile-ios.xcodeproj \
        -scheme mobile-ios \
        -destination "{{ IOS_SIMULATOR }}"

build-test:
    xcodebuild test \
        -project mobile-ios.xcodeproj \
        -scheme mobile-ios \
        -destination "{{ IOS_SIMULATOR }}"

bundle-install:
    bundle install

bundle-add:
    bundle add xxx

bundle-update:
    bundle update

bundle-add-platform:
    bundle lock --add-platform x86_64-darwin-21

bundle-exec-test-coverage:
    bundle exec slather

tuist-install:
    tuist install

tuist-generate:
    tuist generate

tuist-generate-no-open:
    tuist generate --no-open

mint-bootstrap:
    mint bootstrap

lint-swift-format:
    mint run swift-format format . --recursive

lint-swift-format-fix:
    mint run swift-format format . --recursive --in-place

lint-swift-lint:
    mint run swift-format lint . --recursive --strict
