IOS_SIMULATOR := "platform=iOS Simulator,name=iPhone 17,OS=26.0"

bundle-install:
    bundle install

mint-install:
    mint bootstrap

tuist-install:
    tuist install

generate-xcode-workspace:
    tuist generate --no-open

open-xcode-workspace:
    open mobile-ios.xcworkspace

test:
    xcodebuild test \
        -project mobile-ios.xcodeproj \
        -scheme mobile-ios \
        -destination "{{ IOS_SIMULATOR }}"

test-coverage:
    bundle exec slather

lint-swift-format:
    mint run swift-format format . --recursive

lint-swift-format-fix:
    mint run swift-format format . --recursive --in-place

lint-swift-lint:
    mint run swift-format lint . --recursive --strict
