# https://github.com/community-charts/helm-charts/blob/main/charts/mlflow/values.yaml
---
image:
  repository: harbor.hongbomiao.com/hm/mlflow
  tag: 3.7.0.1
imagePullSecrets:
  - name: hm-harbor-secret
initImages:
  mlflowDbMigration:
    repository: harbor.hongbomiao.com/hm/mlflow
    tag: 3.7.0.1
replicaCount: 3
serviceAccount:
  create: true
backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: private-rw.postgresql-xxxxxxxxxxxxxxxxxx.backbone-xxxxxxxxxxxxxxxxxx.msp.us-central1.nebius.cloud
    port: 5432
    database: mlflow_db
    user: mlflow_user
  existingDatabaseSecret:
    name: hm-mlflow-secret
    usernameKey: POSTGRES_USER_NAME
    passwordKey: POSTGRES_PASSWORD
artifactRoot:
  s3:
    enabled: true
    bucket: production-hm-mlflow
    existingSecret:
      name: hm-mlflow-secret
      keyOfAccessKeyId: AWS_ACCESS_KEY_ID
      keyOfSecretAccessKey: AWS_SECRET_ACCESS_KEY
extraEnvVars:
  MLFLOW_OBJECT_STORAGE_ENDPOINT_URL: https://storage.us-central1.nebius.cloud
  MLFLOW_SERVER_CORS_ALLOWED_ORIGINS: https://mlflow.hongbomiao.com
  # https://mlflow.org/docs/latest/self-hosting/security/sso
  OIDC_REDIRECT_URI: https://mlflow.hongbomiao.com/callback
  OIDC_SCOPE: openid,email,profile
  OIDC_DISCOVERY_URL: https://accounts.google.com/.well-known/openid-configuration
  OIDC_GROUP_DETECTION_PLUGIN: google_oidc_group_detection
  PYTHONPATH: /app/plugins
extraSecretNamesForEnvFrom:
  - hm-mlflow-secret
# https://github.com/community-charts/helm-charts/issues/310#issuecomment-3702742603
log:
  enabled: false
extraArgs:
  allowedHosts: mlflow.hongbomiao.com
  uvicornOpts: "--log-level info"
postgresql:
  enabled: false
auth:
  enabled: true
  appName: oidc-auth
  defaultPermission: READ
  existingAdminSecret:
    name: hm-mlflow-secret
    usernameKey: MLFLOW_ADMIN_USER_NAME
    passwordKey: MLFLOW_ADMIN_PASSWORD
  postgres:
    enabled: true
    host: private-rw.postgresql-xxxxxxxxxxxxxxxxxx.backbone-xxxxxxxxxxxxxxxxxx.msp.us-central1.nebius.cloud
    port: 5432
    database: mlflow_auth_db
    user: mlflow_user
    existingSecret:
      name: hm-mlflow-secret
      usernameKey: POSTGRES_USER_NAME
      passwordKey: POSTGRES_PASSWORD
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: mlflow
        topologyKey: kubernetes.io/hostname
resources:
  requests:
    cpu: 10m
    memory: 1700Mi
  limits:
    memory: 2200Mi
nodeSelector:
  environment: production
tolerations:
  - key: environment
    operator: Equal
    value: production
    effect: NoSchedule
extraVolumes:
  - name: oidc-group-detection-plugin
    configMap:
      name: hm-mlflow-oidc-group-detection-config-map
extraVolumeMounts:
  - name: oidc-group-detection-plugin
    mountPath: /app/plugins
