run:
    docker run --rm --interactive --tty \
        --volume="$(pwd)/mediamtx.yml:/mediamtx.yml" \
        --publish=8554:8554 \
        --publish=1935:1935 \
        --publish=8888:8888 \
        --publish=8889:8889 \
        --publish=8890:8890/udp \
        --publish=8189:8189/udp \
        bluenviron/mediamtx:1.15.4

publish:
    gst-launch-1.0 \
        filesrc location=data/video-1.mp4 ! \
        qtdemux name=d \
        d.video_0 ! \
        queue ! \
        h264parse ! \
        rtspclientsink location=rtsp://localhost:8554/video-1 protocols=tcp

subscribe:
    gst-play-1.0 rtsp://localhost:8554/video-1
