# Argo CD
reset-password:
    argocd account bcrypt --password=xxx
    # $2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    kubectl patch secret argocd-secret \
        --namespace=production-hm-argo-cd \
        --patch='{"stringData": {"admin.password": "$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "admin.passwordMtime": "'$(date +%FT%T%Z)'"}}'

sign-in:
    argocd login argo-cd.hongbomiao.com --username=admin

list-projects:
    argocd proj list

list-repositories:
    argocd repo list

list-applications:
    argocd app list

sync-application:
    argocd app sync xxx
