# Argo CD
argo-cd-password-reset:
    argocd account bcrypt --password=xxx
    # $2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    kubectl patch secret argocd-secret \
        --namespace=production-hm-argo-cd \
        --patch='{"stringData": {"admin.password": "$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "admin.passwordMtime": "'$(date +%FT%T%Z)'"}}'

argo-cd-sign-in:
    argocd login argo-cd.internal.hongbomiao.com --username=admin

argo-cd-project-create:
    argocd proj create production-hm --file

argo-cd-project-delete:
    argocd proj delete production-hm

argo-cd-project-list:
    argocd proj list

argo-cd-repo-add:
    argocd repo add git@github.com:hongbo-miao/hongbomiao.com.git --ssh-private-key-path="$HOME/.ssh/hm_argo_cd_id_ed25519" --project=production-hm --upsert

argo-cd-repo-list:
    argocd repo list

argo-cd-repo-remove:
    argocd repo rm git@github.com:hongbo-miao/hongbomiao.com.git

argo-cd-app-create:
    argocd app create xxx --file=xxx.yaml

argo-cd-app-sync:
    argocd app sync xxx
