# Argo CD
argo-cd-password-reset:
    argocd account bcrypt --password=xxx
    # $2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    kubectl patch secret argocd-secret \
        --namespace=production-hm-argo-cd \
        --patch='{"stringData": {"admin.password": "$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "admin.passwordMtime": "'$(date +%FT%T%Z)'"}}'

argo-cd-sign-in:
    argocd login argo-cd.hongbomiao.com --username=admin

argo-cd-project-list:
    argocd proj list

argo-cd-repo-list:
    argocd repo list

argo-cd-app-sync:
    argocd app sync xxx
