pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Summary
      - status-success=Codacy/PR Quality Review
      - status-success=coverage/coveralls
      - status-success=Travis CI - Pull Request
      - status-success=Header rules - hongbomiao
      - status-success=Mixed content - hongbomiao
      - status-success=netlify/hongbomiao/deploy-preview
      - base=master
    actions:
      merge:
        method: merge
