# https://mergify.io

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - author=Hongbo-Miao
      - check-success=Lint
      - check-success=Web - Test
      - check-success=Server - Test
      - check-success=Coverage
      - check-success=Web - Lighthouse
      - check-success=Web - Storybook
      - check-success=Cypress
      - base=master
      - label!=work in progress
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=Lint
      - check-success=Web - Test
      - check-success=Server - Test
      - check-success=Coverage
      - check-success=Web - Lighthouse
      - check-success=Web - Storybook
      - check-success=Cypress
      - base=master
    actions:
      merge:
        method: merge
        strict: true
