# https://mergify.io

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - author=Hongbo-Miao
      - status-success=Summary
      - status-success=Codacy/PR Quality Review
      - status-success=coverage/coveralls
      - status-success=Travis CI - Pull Request
      - status-success=Header rules - hongbomiao
      - status-success=Mixed content - hongbomiao
      - status-success=netlify/hongbomiao/deploy-preview
      - base=master
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=Summary
      - status-success=Codacy/PR Quality Review
      - status-success=coverage/coveralls
      - status-success=Travis CI - Pull Request
      - status-success=Header rules - hongbomiao
      - status-success=Mixed content - hongbomiao
      - status-success=netlify/hongbomiao/deploy-preview
      - base=master
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=Summary
      - status-success=Codacy/PR Quality Review
      - status-success=coverage/coveralls
      - status-success=Travis CI - Pull Request
      - status-success=Header rules - hongbomiao
      - status-success=Mixed content - hongbomiao
      - status-success=netlify/hongbomiao/deploy-preview
      - base=master
    actions:
      merge:
        method: merge
        strict: true
