# https://docs.mergify.io

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - author=Hongbo-Miao
      - check-success=Lint (JavaScript, CSS, Solidity, Markdown)
      - check-success=Lint (Go)
      - check-success=Lint (Protocol Buffers)
      - check-success=Lint (Python)
      - check-success=Lint (Dockerfile)
      - check-success=Lint (Kubernetes)
      - check-success=Lint (Shell)
      - check-success=Static Type Check (TypeScript)
      - check-success=Static Type Check (Python)
      - check-success=Web - Test
      - check-success=Web - Lighthouse
      - check-success=Web - Storybook
      - check-success=Mobile - Test
      - check-success=API - Test
      - check-success=API - Stryker
      - check-success=OPA - Test
      - check-success=Prometheus - Test
      - check-success=Cypress
      - base=main
      - label!=work in progress
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=Lint (JavaScript, CSS, Solidity, Markdown)
      - check-success=Lint (Go)
      - check-success=Lint (Protocol Buffers)
      - check-success=Lint (Python)
      - check-success=Lint (Dockerfile)
      - check-success=Lint (Kubernetes)
      - check-success=Lint (Shell)
      - check-success=Static Type Check (TypeScript)
      - check-success=Static Type Check (Python)
      - check-success=Web - Test
      - check-success=Web - Lighthouse
      - check-success=Web - Storybook
      - check-success=Mobile - Test
      - check-success=API - Test
      - check-success=API - Stryker
      - check-success=OPA - Test
      - check-success=Prometheus - Test
      - check-success=Cypress
      - check-failure!=renovate/artifacts
      - base=main
    actions:
      merge:
        method: merge
        strict: true
