language: node_js
node_js:
  - "12"

cache: yarn

notifications:
  email: false

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test

    - stage: coverage
      script:
        - yarn coverage
      after_script:
        # upload coverage reports
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn coveralls

    - stage: lighthouse
      if: type = pull_request
      script:
        - yarn run lh -- "$(wait-for-netlify-preview)"
