language: node_js
node_js:
  - "12"

branches:
  only:
    - master

cache: yarn

notifications:
  email: false

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn lint:css
        - yarn test
        - yarn test:coverage
      after_script:
        # Upload coverage reports to Coveralls
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn coveralls

    - stage: storybook
      script:
        # Run chromatic only when a build does not originate from a pull request (push build), or when it is a pull request build originating from a fork
        - |
          if [[ $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then
            yarn run chromatic --exit-zero-on-changes
          fi

    - stage: lighthouse
      script:
        - yarn build
        - yarn run lighthouse
      addons:
        chrome: stable
