language: node_js
node_js:
  - "14"

branches:
  only:
    - master

cache: yarn

notifications:
  email: false

env:
  global:
    - LIGHTSTEP_TOEKN=$LIGHTSTEP_TOEKN
    - REACT_APP_LIGHTSTEP_TOEKN=$REACT_APP_LIGHTSTEP_TOEKN

install:
  - yarn install --frozen-lockfile
  - cd $TRAVIS_BUILD_DIR/client && yarn install --frozen-lockfile
  - cd $TRAVIS_BUILD_DIR/server && yarn install --frozen-lockfile

jobs:
  include:
    - stage: Test
      name: "Lint"
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn lint
        - yarn lint:css

    - stage: Test
      name: "Test - Client"
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        - yarn test

    - stage: Test
      name: "Test - Server"
      before_script:
        - cd $TRAVIS_BUILD_DIR/server
      script:
        - yarn test

    - stage: Test
      name: "Test Coverage"
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn test:coverage
      after_script:
        # Upload coverage reports to Coveralls
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn test:coverage:report

    - stage: Test
      name: "Storybook - Client"
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        # Run chromatic only when a build does not originate from a pull request (push build), or when it is a pull request build originating from a fork
        - |
          if [[ $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then
            yarn run chromatic --exit-zero-on-changes
          fi

    - stage: Test
      name: "Lighthouse - Client"
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        # Set CI=false to let Travis pass "Treating warnings as errors because process.env.CI = true."
        # caused by https://github.com/lightstep/opentelemetry-exporter-js/issues/12
        - CI=false yarn build
        - yarn run lighthouse
      addons:
        chrome: stable

    - stage: Deploy
      before_deploy:
        - cd $TRAVIS_BUILD_DIR
      deploy:
        provider: heroku
        api_key:
          secure: "sx1p98NzubuaCaaGTWnOKFsStMLOgQMgO9k7aK85ROrRJ653/i9n/e1/Y4ESDPI2Sj5AFHgod0SCkL6fgKyvFje3RNKSbNyxJreaezxJ5fiDMkOHwEqGtF7AfsjX5yhNkgejBxELkapIAhlEjthkpFhwN9F5a+WKj3iTlh1Bl6Mv3aJmf98m/G2c97caIxjb5e9jAsijPSnIITCs70y2nwhyShA7cusLgxcRog78Qs+9mL5VLx+ZlA5HcdKj+OCuasDggadUVDAJhitNgUJ4jVO+qEGvXxIjZUgu2eofA7Zc5HxAhu8ocbpcLHb9pVqIDkOxtgABi27INM4QHmrGk8nyVn1yLKHKG4hcC/pzd161Yf+9ueBC+PUP6JwAIoobDINac5zlU/ORop70Rtb1abKbiPf1s023ufvtMcHd1GW9CwKyD4U3fBWfn15uzlge9xrS/xoG6ZCEd10EqX08ezShxUKgY+79GjOGFgX1H47tFCUuU+BwEOZLWmDQfZ0sRwTm//L9iRticeGL1h797LpNiC50chdqTuoYVBSGtxpRCedjrVFpSDMfBSS33Ve0KxcoQf5Cm5Fgil3a3r2MRMxnvfXNp6CW+uXqg1avPNOdnlf3SUMGgwVEIZMUa5GlNeilgfEWDbfexXt6QhfAkDQVTawaYeG5afVEi6IKIWE="
        app: hongbomiao
        on:
          branch: master
