group: edge

os: linux
dist: focal
arch: arm64-graviton2

language: node_js
node_js:
  - "14"

branches:
  only:
    - master

addons:
  apt:
    packages:
      # For Cypress on Ubuntu 16+, https://github.com/cypress-io/cypress-documentation/pull/1647
      - libgconf-2-4

cache:
  yarn: true
  directories:
    # For Cypress, https://docs.cypress.io/guides/guides/continuous-integration.html#Caching
    - ~/.cache

notifications:
  email: false

install:
  - yarn install --frozen-lockfile
  - cd $TRAVIS_BUILD_DIR/client && yarn install --frozen-lockfile
  - cd $TRAVIS_BUILD_DIR/server && yarn install --frozen-lockfile

jobs:
  include:
    - stage: Test
      name: "Lint"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn lint:js
        - yarn lint:css

    - stage: Test
      name: "Test - Client"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        - yarn test

    - stage: Test
      name: "Test - Server"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR/server
      script:
        - yarn test

    - stage: Test
      name: "Test Coverage"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn test:coverage
      after_script:
        - yarn test:coverage:publish

    - stage: Test
      name: "Lighthouse - Client"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        - yarn build
        - yarn run lighthouse
      addons:
        chrome: stable

    - stage: Test
      name: "Storybook - Client"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        - yarn run storybook:publish --exit-zero-on-changes

      # https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
    - stage: Test
      name: "Cypress"
      if: type = pull_request
      before_script:
        - cd $TRAVIS_BUILD_DIR/client && yarn build
        - cd $TRAVIS_BUILD_DIR && cp -r client/build/ server/dist/
        - cd $TRAVIS_BUILD_DIR/server && yarn build
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn test:cypress:headless:ci

    - stage: Deploy
      name: "Heroku"
      if: branch = master && type = push && fork = false
      before_deploy:
        - cd $TRAVIS_BUILD_DIR
      deploy:
        provider: heroku
        api_key:
          secure: "sx1p98NzubuaCaaGTWnOKFsStMLOgQMgO9k7aK85ROrRJ653/i9n/e1/Y4ESDPI2Sj5AFHgod0SCkL6fgKyvFje3RNKSbNyxJreaezxJ5fiDMkOHwEqGtF7AfsjX5yhNkgejBxELkapIAhlEjthkpFhwN9F5a+WKj3iTlh1Bl6Mv3aJmf98m/G2c97caIxjb5e9jAsijPSnIITCs70y2nwhyShA7cusLgxcRog78Qs+9mL5VLx+ZlA5HcdKj+OCuasDggadUVDAJhitNgUJ4jVO+qEGvXxIjZUgu2eofA7Zc5HxAhu8ocbpcLHb9pVqIDkOxtgABi27INM4QHmrGk8nyVn1yLKHKG4hcC/pzd161Yf+9ueBC+PUP6JwAIoobDINac5zlU/ORop70Rtb1abKbiPf1s023ufvtMcHd1GW9CwKyD4U3fBWfn15uzlge9xrS/xoG6ZCEd10EqX08ezShxUKgY+79GjOGFgX1H47tFCUuU+BwEOZLWmDQfZ0sRwTm//L9iRticeGL1h797LpNiC50chdqTuoYVBSGtxpRCedjrVFpSDMfBSS33Ve0KxcoQf5Cm5Fgil3a3r2MRMxnvfXNp6CW+uXqg1avPNOdnlf3SUMGgwVEIZMUa5GlNeilgfEWDbfexXt6QhfAkDQVTawaYeG5afVEi6IKIWE="
        app: hongbomiao
        on:
          branch: master
