language: node_js
node_js:
  - "12"

cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: lint
      install: yarn install --frozen-lockfile
      script: yarn lint
    - stage: test
      install: yarn install --frozen-lockfile
      script: yarn test
    - stage: coverage
      install: yarn install --frozen-lockfile
      script: yarn coverage
      after_script:
        # Upload coverage reports
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn coveralls
    - stage: lighthouse
      if: type = pull_request
      install: yarn install --frozen-lockfile
      script: yarn lh "$(wait-for-netlify-preview)"
