language: node_js
node_js:
  - "12"

cache: yarn

jobs:
  include:
    - stage: lighthouse
      if: type = pull_request
      install: yarn install --frozen-lockfile
      script: yarn lh "$(wait-for-netlify-preview)"
