language: node_js
node_js:
  - "14"

branches:
  only:
    - master

cache: yarn

notifications:
  email: false

install:
  - yarn install --frozen-lockfile
  - cd $TRAVIS_BUILD_DIR/client && yarn install --frozen-lockfile
  - cd $TRAVIS_BUILD_DIR/server && yarn install --frozen-lockfile

jobs:
  include:
    - stage: Test
      name: "Lint"
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn lint
        - yarn lint:css

    - stage: Test
      name: "Test - Client"
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        - yarn test

    - stage: Test
      name: "Test - Server"
      before_script:
        - cd $TRAVIS_BUILD_DIR/server
      script:
        - yarn test

    - stage: Test
      name: "Test Coverage"
      before_script:
        - cd $TRAVIS_BUILD_DIR
      script:
        - yarn test:coverage
      after_script:
        # Upload coverage reports to Coveralls
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn test:coverage:report

    - stage: Test
      name: "Storybook - Client"
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        # Run chromatic only when a build does not originate from a pull request (push build), or when it is a pull request build originating from a fork
        - |
          if [[ $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then
            yarn run chromatic --exit-zero-on-changes
          fi

    - stage: Test
      name: "Lighthouse - Client"
      before_script:
        - cd $TRAVIS_BUILD_DIR/client
      script:
        - yarn build
        - yarn run lighthouse
      addons:
        chrome: stable
