language: node_js
node_js:
  - "12"

branches:
  only:
    - master

cache: yarn

notifications:
  email: false

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn lint:css
        - yarn test
        - yarn test:coverage
      after_script:
        # Upload coverage reports to Coveralls
        - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN yarn coveralls

    - stage: storybook
      if: type = push
      script:
        - CHROMATIC_APP_CODE=$CHROMATIC_APP_CODE yarn run chromatic

    - stage: lighthouse
      if: type = pull_request
      script:
        - yarn run lh --perf 70 --pwa 70 --a11y 70 --bp 70 --seo 70 "$(wait-for-netlify-preview)"
