FROM nginx:1.19.3-alpine

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY ./server/private/ssl/hongbomiao.crt /etc/ssl/hongbomiao.crt
COPY ./server/private/ssl/hongbomiao.key /etc/ssl/hongbomiao.key
