version: '3.7'

services:
  # Server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4001:3001'
    environment:
      - NODE_ENV=development

  # OpenTelemetry Collector
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    command: [
      "--config=/conf/opentelemetry-collector.config.yaml",
      "--log-level=DEBUG"
    ]
    volumes:
      - ./opentelemetry-collector.config.yaml:/conf/opentelemetry-collector.config.yaml
    ports:
      - "9464:9464"
      - "55680:55680"
      - "55681:55681"
    depends_on:
      - jaeger-collector
      - zipkin-all-in-one

  # Jaeger
  jaeger-collector:
    image: jaegertracing/jaeger-opentelemetry-collector:latest
    command: [
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--es.server-urls=http://elasticsearch:9200"
    ]
    ports:
      - "14250"
      - "14268"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - LOG_LEVEL=debug
    restart: on-failure
    depends_on:
      - elasticsearch

  jaeger-agent:
    image: jaegertracing/jaeger-opentelemetry-agent:latest
    command: [
      "--config=/config/otel-agent-config.yml",
      "--reporter.grpc.host-port=jaeger-collector:14250"
    ]
    volumes:
      - ./:/config/:ro
    ports:
      - "6831/udp"
      - "6832/udp"
      - "5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    command: [
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--es.server-urls=http://elasticsearch:9200"
    ]
    ports:
      - "16686:16686"
      - "16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - LOG_LEVEL=debug
    restart: on-failure
    depends_on:
      - elasticsearch

  # Elasticsearch
  elasticsearch:
    # https://www.docker.elastic.co/r/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9
    environment:
      - discovery.type=single-node
    ports:
      - "9200/tcp"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
