FROM nginx:1.19.5-alpine

COPY server/private/ssl/hongbomiao.crt.example /etc/ssl/hongbomiao.crt
COPY server/private/ssl/hongbomiao.key.example /etc/ssl/hongbomiao.key

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
