version: '3.7'

services:
  hongbomiao.com:
    container_name: hongbomiao.com
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4001:3001'
    environment:
      - NODE_ENV=development
