apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hongbomiao.com
build:
  artifacts:
  - image: hongbomiao/hongbomiao-api
    docker:
      dockerfile: Dockerfile.api.development
deploy:
  kubectl:
    manifests:
    - kubernetes/ingress-service.yaml
    - kubernetes/api-cluster-ip-service.yaml
    - kubernetes/api-deployment.yaml
