# https://skaffold.dev/docs/references/yaml/

apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: hongbomiao.com
build:
  artifacts:
  - image: hongbomiao/web
    context: .
    docker:
      dockerfile: web/Dockerfile
  - image: hongbomiao/hm-api-go:latest
    context: .
    docker:
      dockerfile: api-go/build/package/Dockerfile.api
    sync:
      manual:
        - src: "*.go"
          dest: .
  - image: hongbomiao/hm-api-go-grpc:latest
    context: .
    docker:
      dockerfile: api-go/build/package/Dockerfile.grpc
    sync:
      manual:
        - src: "*.go"
          dest: .
deploy:
  kubectl:
    manifests:
    - kubernetes/config/*.yaml
