# https://skaffold.dev/docs/references/yaml/

apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: hongbomiao.com
build:
  artifacts:
  - image: hongbomiao/web
    context: .
    docker:
      dockerfile: web/Dockerfile
  - image: hongbomiao/hongbomiao-api-go
    context: .
    docker:
      dockerfile: api-go/Dockerfile.api
    sync:
      manual:
        - src: "*.go"
          dest: .
  - image: hongbomiao/hongbomiao-api-go-grpc
    context: .
    docker:
      dockerfile: api-go/Dockerfile.grpc
    sync:
      manual:
        - src: "*.go"
          dest: .
deploy:
  kubectl:
    manifests:
    - kubernetes/*.yaml
