argo-cd-app-create:
    argocd app create production-hm-promtail --file=argo-cd-manifests/hm-promtail-application.yaml

argo-cd-app-update:
    argocd app create production-hm-promtail --file=argo-cd-manifests/hm-promtail-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-promtail --yes
