create:
    argocd app create production-hm-priority-class --file=argo-cd-manifests/hm-priority-class-application.yaml

update:
    argocd app create production-hm-priority-class --file=argo-cd-manifests/hm-priority-class-application.yaml --upsert

delete:
    argocd app delete production-hm-priority-class --yes
