---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hm-apicurio-registry-secret
  namespace: production-hm-apicurio-registry
spec:
  encryptedData:
    password: AgADpcoMuT4DEgT59glzSizZGuyVNiC29jNl6ByxdxblfFXR9qolcY5pyZmt8uLHAybnnMHjW+wYD1/8gFnHOjvorlLzy17NPiRoLEjGBeG9+X9YYDKl7MlOsa+EPcJUzOGgT6tG/+Il2bnCLcER5JuxOxY1sG/nmfCbbuwTXNlRyDPu1VEu0LCH85bUfG6C8WIuonGPQiNGXFLX3Y2PfQgWiXh7muPkQw6XLJUoXynG7MeU7KO4zrmC7SUJm5TyQYq6C9RxGk4ctr22greo3mxo+i6qf1weKEZNwrgK5q2wYkWexz340ZOIHbnKFWKArzaLMGevp8OhIG5SricxmaASjF/vzLgtrdCWg57vzOFwF68lax8IROyzo03k+P9KMPjgDnkqMTT9/P+6p4scBSPF69hiWeciY6PQ58okQ+uureeSAO2U994Y6+cnKjhRRHxylpzfkd+dOe0l2SBrGVvv8VyddymOboPrZ/Dhc3UUPwNGl++n7tXKZPPnAg9Y3k/y+Ywz8mljA0qkOcDnasfth1/KLOkO/ZvMUbf0tlwek6DPPHgGZucPjKcT9q+wOJVvXmVXRfwEGXZ6B+pVCthsGgxIqdY5kEOE0MSBL3PBszkSa0SKrg9rzlzn3S2UXsi6JcRoNK097JykXcKngeZStkB8UPIS0n4AFN+3p5vmXjGMdrkZqzvhTXMNklbOEUFO+g4=
    username: AgB2aZzWxFONrWXGKYT521W40rvHSfIj/d9soJvwimtmGmw2Wzm7gLgy5c3dvUMM4+rUqEOYJkNQ5ofEg7xBAHWw/XjAdcEbDKIE94cVmB9xks/t2djKQ7YSQKgv0ovcwrirOEXNmtHVHWgi7Aom2h31ZDiRX9oJ/JKP7d27unj8LmjkNm+B9Z59xO61fHVYh9FtewcTpztZfaobH/BxDxKnuhwnvA1NQo5K6a7G5Ek5NmPOBNXMD0eBhDZ2bT95zgdC96Gdy3av/WyuSDAsmMtJ3h8nHrC5g+SV7XVdRGNfQNDLyOWOKz471n+Fp1i9Dzb71t19474JnMT6DKukPtRHL0tZH16WWz5w9Zdpz0R/W2waPzBIULSSrmMUcfpgSj5SUzistaZXFVWultHxLvDMwIeWxQzGSLt+bu5oOdZ6Ei4io5tTX9UMqrPu9+CvzKtZtcLUoYBPLjiFVXA14FwoT7qKz3Fg5f9EBEfnmIilxpM8MwQlTenkWLXY0eG+1TE5hxr8HRoVtER03cC3Ss9SwcUo5C0i/fz5NP7d9m8+U0A9yR0Uf/Vfk7qa+mHJB5m2QpNh+k9vtOeP59MaxNc5Yz+uRKpFmYXnAfyt2KqSx7z9ObG6BtaBL5Tlp85da2caRGqyir6nes70Tu6nbB2/pykfA4WCfigzsb0FLUbqRaCLyxxwtIIzaT/0tve3OLlujX0=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apicurio-registry-secret
        app.kubernetes.io/part-of: production-hm-apicurio-registry
      name: hm-apicurio-registry-secret
      namespace: production-hm-apicurio-registry
    type: Opaque
