zellij-install:
	sudo snap install zellij --classic
zellij-session-list:
	zellij list-sessions
zellij-session-new:
	zellij --session=my-session
zellij-session-attach:
	zellij attach hongbo
zellij-session-dettach:
	# ctrl + o, d
