create:
    argocd app create production-hm-alloy --file=argo-cd-manifests/hm-alloy-application.yaml

update:
    argocd app create production-hm-alloy --file=argo-cd-manifests/hm-alloy-application.yaml --upsert

delete:
    argocd app delete production-hm-alloy --yes
