argo-cd-app-create:
    argocd app create production-hm-tempo --file=argo-cd-manifests/hm-tempo-application.yaml

argo-cd-app-update:
    argocd app create production-hm-tempo --file=argo-cd-manifests/hm-tempo-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-tempo --yes
