FROM golang:1.16.5-alpine AS base
WORKDIR /usr/src/app


FROM base AS api-go
ENV GIN_MODE=release

COPY ["api-go/go.mod", "api-go/go.sum", "./"]
RUN go mod download

COPY api-go ./
RUN go build -o ./out/cmd/grpc/ ./cmd/grpc/main.go

EXPOSE 5000
CMD ["./out/cmd/grpc/main"]
