FROM golang:1.16.5-alpine AS base
WORKDIR /usr/src/app


FROM base AS release
COPY ["api-go/go.mod", "api-go/go.sum", "./"]
RUN go mod download

COPY api-go ./
RUN go build -o ./out/cmd/api/ ./cmd/api/main.go

EXPOSE 5000
CMD ["./out/cmd/api/main"]
