update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

set-up:
    # Download nuScenes "Full dataset (v1.0) - Mini - Metadata and sensor file blobs (3.88 GB)" from https://www.nuscenes.org/download
    # Extract to data/v1.0-mini/

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
