update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

hugging-face-sign-in:
    hf auth login

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
