seal-secret:
    cat secrets/hm-ray-cluster-secret.unsealed.yaml | \
    kubeseal \
        --cert=https://sealed-secrets.hongbomiao.com/v1/cert.pem \
        --format=yaml \
        > kubernetes-manifests/hm-ray-cluster-secret.yaml

ray-cluster-delete:
    kubectl delete raycluster hm-ray-cluster --namespace=production-hm-ray-cluster
