create:
    argocd app create production-hm-confluent-schema-registry --file=argo-cd-manifests/hm-confluent-schema-registry-application.yaml

update:
    argocd app create production-hm-confluent-schema-registry --file=argo-cd-manifests/hm-confluent-schema-registry-application.yaml --upsert

delete:
    argocd app delete production-hm-confluent-schema-registry --yes
