---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production-nimtable
  namespace: production-hm-argo-cd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:hongbo-miao/hongbomiao.com.git
        revision: main
        directories:
          - path: kubernetes/argo-cd/projects/nebius/production-hm/nimtable/environments/*
  template:
    metadata:
      name: '{{.path.basename}}-nimtable'
    spec:
      project: production-hm
      source:
        repoURL: git@github.com:hongbo-miao/hongbomiao.com.git
        targetRevision: main
        path: '{{.path.path}}/kubernetes-manifests'
      destination:
        namespace: '{{.path.basename}}-hm-nimtable'
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
