argo-cd-app-create:
    argocd app create production-hm-doris-operator --file=argo-cd-manifests/hm-doris-operator-application.yaml

argo-cd-app-update:
    argocd app create production-hm-doris-operator --file=argo-cd-manifests/hm-doris-operator-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-doris-operator --yes
