---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hm-harbor-secret
  namespace: production-hm-mlflow
spec:
  encryptedData:
    .dockerconfigjson: AgAcsnATlLUbBDX01C8NcMktvcon9eDRe3fUCf8zgNoLr/aosI08QvS3ipP+KBxuH2h8gI4jb6ehF+3ZXPMo4SOoutR75O4ra3bovQQdQnVlJ9lStU4ZINwaXb6RDJfq1STHGcMAQgjDmXi5W+ziZD7np+sGJRuw1jszjLO+jwiER5+wJJlOxq4pbkIJ2ndHXneC8q4YUvfvaCKFvtCyF50h86OUHSrhjZyj1qhOlrWu+dOwnq90UK3aNr2qIurS1ZP3+TdmB834DF8NmYfP4JhbHOD5YmtQ0whJ6yMjkxvxgy7DIcDWBxaZm/B59dV+wP7ZrcOf6LTAmWbrX5mY4M6w6d3SzhP2IDp7rKVmKu1jaEq6aEJeY6VXcKn09UdxbQflT4i8Usd7oyX76fLxdmAminxWfRCh+z8/qoBGtZYBNk7/CBk+4+cDo2O4+sDAOSgUYh3B/UPBKtm3SW2RqKUQrygF89ZyYb684/YdTzoLvfluH8pVR4GeLAmCbvRGv2zMz2s8Vchlu0howUA6BrQgHQkmtAZtTy9jB3O/5yMmYjfaqUEOic1xZubsYifjVL8DfH5dbb8mX0YwZdjkTQuYNZZsALQcNPb4ccupUiMet1RijeXm5wMmd/iP/L9YJEi1INo1tidABpuYqtuMPaMJYfB312aG+dtQf+7FHCUczYyoYBaaD1R9bYyNl18im2SexNNoX2nXOYxaPuPXWWzZ4vxu+ZW5oNhZWSfK+EJ/oOOjNtS7dPRsDtU/NS4E4y86r9YxRKyfZIUP+0t6RxNSH/44mklRlbPBVV6NRnv/V2bQtS01Naj3ZFYE6k2zc+0RAjxUeRXUQ+Bb5PqjnYI2BOBEUmzXbD6RMmEYByebvqwAccvkMNSYjwPe6II3zvqKUWl9qxIuhJIMAebLE1te2VAUGf8J0Q4Y8SxWihi+FF7jN6wQG9q7H5rYm3xPd1k=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        app.kubernetes.io/part-of: production-hm-mlflow
      name: hm-harbor-secret
      namespace: production-hm-mlflow
    type: kubernetes.io/dockerconfigjson
