veristand-deploy:
	"C:\Program Files\National Instruments\VeriStand 2024\veristand-server.exe" deploy "C:\Users\Public\Documents\National Instruments\NI VeriStand 2024\Examples\Stimulus Profile\Engine Demo\Engine Demo.nivssdf"
veristand-undeploy:
	"C:\Program Files\National Instruments\VeriStand 2024\veristand-server.exe" undeploy "C:\Users\Public\Documents\National Instruments\NI VeriStand 2024\Examples\Stimulus Profile\Engine Demo\Engine Demo.nivssdf"
