uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

edit:
    uv run poe edit

run:
    uv run poe run

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
