update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

edit:
    uv run poe edit

run:
    uv run poe run

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
