traefik:
    traefik --configfile=traefik.yaml

docker-build:
    docker build --file=Dockerfile --tag=ghcr.io/hongbo-miao/hm-traefik:latest .

docker-push:
    docker push ghcr.io/hongbo-miao/hm-traefik:latest
