conda-create:
	conda create --name=hm-prefect python=3.10
conda-env-remove:
	conda env remove --name=hm-prefect
conda-activate:
	conda activate hm-airflow
conda-deactivate:
	conda deactivate
conda-env-list:
	conda env list
conda-list-packages:
	conda list

pip-install:
	pip install --upgrade prefect

prefect-start:
	prefect orion start

workflow-start:
	python greet.py
