create:
    argocd app create production-hm-opencost --file=argo-cd-manifests/hm-opencost-application.yaml

update:
    argocd app create production-hm-opencost --file=argo-cd-manifests/hm-opencost-application.yaml --upsert

delete:
    argocd app delete production-hm-opencost --yes
