uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-dev:
    uv run poe dev --dataset=ogbg-molhiv --gnn=gcn

uv-run-dev-debug:
    uv run poe dev --dataset=ogbg-molhiv --gnn=gcn --feature=simple --epochs=2

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage
