uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev --dataset=ogbg-molhiv --gnn=gcn

dev-debug:
    uv run poe dev --dataset=ogbg-molhiv --gnn=gcn --feature=simple --epochs=2

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
