cargo-clean:
	cargo clean
cargo-update:
	cargo update
cargo-test:
	cargo test --all-features
cargo-build:
	cargo build
cargo-run-development:
	cargo run
cargo-run-production:
	cargo run --release

lint-rust-rustfmt:
	cargo fmt --all -- --check
lint-rust-rustfmt-fix:
	cargo fmt --all
lint-rust-clippy:
	cargo clippy
lint-rust-clippy-fix:
	cargo clippy --fix --allow-dirty --allow-staged
