poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install --no-root
poetry-add:
	poetry add xxx
poetry-add-dev:
	poetry add xxx --group=dev
poetry-run-dev:
	poetry run poe dev

download-tdms-sample:
	# https://www-personal.acfr.usyd.edu.au/zubizarreta/EDatabase.php
	curl http://www-personal.acfr.usyd.edu.au/zubizarreta/f/exampleMeasurements.tdms > data/exampleMeasurements.tdms
