initialize:
    # vagrant init generic/debian11
    vagrant init bento/debian-11.2-arm64

up:
    vagrant up --provider=parallels

suspend:
    vagrant suspend

halt:
    vagrant halt

destroy:
    vagrant destroy --force

ssh:
    vagrant ssh

status:
    vagrant status
