create:
    argocd app create production-hm-kuberay-operator --file=argo-cd-manifests/hm-kuberay-operator-application.yaml

update:
    argocd app create production-hm-kuberay-operator --file=argo-cd-manifests/hm-kuberay-operator-application.yaml --upsert

delete:
    argocd app delete production-hm-kuberay-operator --yes
