sealed-secrets-seal-hm-prometheus-prefect-exporter-secret:
    cat secrets/hm-prometheus-prefect-exporter-secret.unsealed.yaml | \
    kubeseal \
        --cert=https://sealed-secrets.hongbomiao.com/v1/cert.pem \
        --format=yaml \
        > kubernetes-manifests/hm-prometheus-prefect-exporter-secret.yaml
