sealed-secrets-seal-hm-prometheus-prefect-exporter-secret:
    cat secrets/hm-prometheus-prefect-exporter-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/hm-prometheus-prefect-exporter-secret.yaml
