argo-cd-app-create:
	argocd app create hm-sealed-secrets --file=manifests/hm-sealed-secrets.yaml
argo-cd-app-update:
	argocd app create hm-sealed-secrets --file=manifests/hm-sealed-secrets.yaml --upsert
