uv-install-python:
	uv python install
uv-update-lock-file:
	uv lock
uv-install-dependencies:
	uv sync --dev

uv-run-dev:
	uv run poe dev
uv-run-test:
	uv run poe test
uv-run-test-coverage:
	uv run poe test-coverage

curl-download-dog:
	curl --silent --fail --show-error --location --output data/dog.jpg https://i.ibb.co/bLvrvRV/shiba-inu-dog.jpg
