argo-cd-app-create:
    argocd app create production-hm-velero --file=argo-cd-manifests/hm-velero-application.yaml

argo-cd-app-update:
    argocd app create production-hm-velero --file=argo-cd-manifests/hm-velero-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-velero --yes
