update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

download-dataset:
    curl --silent --fail --show-error --location https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz | tar --extract --directory=data
