uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

download-dataset:
    curl --fail --show-error --location https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz | tar --extract --directory=data
