update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

# Pulumi
sign-in:
    pulumi login s3://hongbomiao-pulumi-bucket

initialize:
    pulumi new aws-python

up:
    export PULUMI_CONFIG_PASSPHRASE_FILE="passphrase.txt" && pulumi up

down:
    export PULUMI_CONFIG_PASSPHRASE_FILE="passphrase.txt" && pulumi destroy

stack-list:
    pulumi stack ls

stack-initialize:
    pulumi stack init development

convert:
    pulumi convert --from=tofu --language=python --out=my-pulumi --generate-only
