poetry-env-use:
	poetry env use python3.12
poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install

libmagic-install:
	brew install libmagic

poetry-run-dev:
	poetry run poe dev
