create:
    argocd app create production-hm-s3-browser --file=argo-cd-manifests/hm-s3-browser-application.yaml

update:
    argocd app create production-hm-s3-browser --file=argo-cd-manifests/hm-s3-browser-application.yaml --upsert

delete:
    argocd app delete production-hm-s3-browser --yes
