argo-cd-app-create:
	argocd app create hm-metrics-server --file=manifests/hm-metrics-server.yaml
argo-cd-app-update:
	argocd app create hm-metrics-server --file=manifests/hm-metrics-server.yaml --upsert
