apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: hm
  annotations:
    linkerd.io/inject: enabled
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: web
          image: hongbomiao/hongbomiao-web:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
