uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-dev:
    uv run poe dev

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage

zip-pytorch-mnist:
    cd .. && \
    zip -r pytorch-mnist.zip pytorch-mnist \
        -x 'pytorch-mnist/.venv/*'

# In SageMaker Noteebok instance's JupyterLab terminal
unzip-pytorch-mnist:
    cd SageMaker/
    unzip pytorch-mnist.zip
