vagrant-install:
	brew install --cask vagrant
	brew install --cask vagrant-manager

vagrant-help:
	vagrant help

vagrant-box-list:
	vagrant box list
vagrant-box-outdated:
	vagrant box outdated
vagrant-box-update:
	vagrant box update
vagrant-box-add:
	vagrant box add xxx
vagrant-box-remove:
	vagrant box remove xxx
vagrant-box-help:
	vagrant help box

vagrant-plugin-list:
	vagrant plugin list
vagrant-plugin-install:
	vagrant plugin install xxx
vagrant-plugin-uninstall:
	vagrant plugin uninstall xxx
vagrant-plugin-help:
	vagrant help plugin
