vagrant-install:
	brew install --cask vagrant
	brew install --cask vagrant-manager
vagrant-up:
	vagrant up
vagrant-ssh:
	vagrant ssh
vagrant-suspend:
	vagrant suspend
vagrant-halt:
	vagrant halt
vagrant-destroy:
	vagrant destroy
vagrant-status:
	vagrant status
vagrant-ssh:
	vagrant ssh
vagrant-help:
	vagrant help
vagrant-box-list:
	vagrant box list
vagrant-box-outdated:
	vagrant box outdated
vagrant-box-update:
	vagrant box update
vagrant-box-add:
	vagrant box add xxx
vagrant-box-remove:
	vagrant box remove xxx
vagrant-box-help:
	vagrant help box
vagrant-plugin-list:
	vagrant plugin list
vagrant-plugin-install:
	vagrant plugin install vagrant-vbguest
vagrant-plugin-uninstall:
	vagrant plugin uninstall vagrant-vbguest
vagrant-plugin-help:
	vagrant help plugin
