terraform-init:
	terraform init
terraform-update-lock-file:
	terraform init -upgrade
terraform-reconfigure:
	terraform init -reconfigure
terraform-plan:
	terraform plan -parallelism=8
terraform-apply:
	terraform apply -auto-approve -parallelism=8
terraform-refresh:
	terraform refresh
terraform-destroy:
	terraform destroy

terraform-get:
	terraform get
terraform-graph: # http://www.webgraphviz.com
	terraform graph
terraform-login:
	terraform login
terraform-validate:
	terraform validate
terraform-show:
	terraform show
terraform-state-list:
	terraform state list
terraform-output:
	terraform output
