argo-cd-app-create:
	argocd app create hm-prometheus --file=argo-cd-manifests/hm-prometheus.yaml
argo-cd-app-update:
	argocd app create hm-prometheus --file=argo-cd-manifests/hm-prometheus.yaml --upsert
