uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

publish-development-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=harbor.hongbomiao.com/hm/prefect-daft-analysis:development . && \
    docker push harbor.hongbomiao.com/hm/prefect-daft-analysis:development

publish-production-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=harbor.hongbomiao.com/hm/prefect-daft-analysis:latest . && \
    docker push harbor.hongbomiao.com/hm/prefect-daft-analysis:latest

deploy-development:
    uv run poe deploy --environment=development

deploy-production:
    uv run poe deploy --environment=production

run-development:
    uv run poe run -- hm-daft-analysis/development-hm-daft-analysis

run-production:
    uv run poe run -- hm-daft-analysis/production-hm-daft-analysis
