show-gpu:
    nvidia-smi

show-gpu-communication-matrix:
    nvidia-smi topo --matrix

cuda-toolkit-install-windows:
    # https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

cuda-toolkit-install-wsl-2:
    # https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local
    wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
    sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
    wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda-repo-wsl-ubuntu-12-8-local_12.8.0-1_amd64.deb
    sudo dpkg --install cuda-repo-wsl-ubuntu-12-8-local_12.8.0-1_amd64.deb
    sudo cp /var/cuda-repo-wsl-ubuntu-12-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
    sudo apt-get update
    sudo apt-get --yes install cuda-toolkit-12-8

cuda-toolkit-install-ubuntu-24:
    # https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=24.04&target_type=deb_local
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-ubuntu2404.pin
    sudo mv cuda-ubuntu2404.pin /etc/apt/preferences.d/cuda-repository-pin-600
    wget https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda-repo-ubuntu2404-12-9-local_12.9.1-575.57.08-1_amd64.deb
    sudo dpkg --install cuda-repo-ubuntu2404-12-9-local_12.9.1-575.57.08-1_amd64.deb
    sudo cp /var/cuda-repo-ubuntu2404-12-9-local/cuda-*-keyring.gpg /usr/share/keyrings/
    sudo apt-get update
    sudo apt-get --yes install cuda-toolkit-12-9
    # Driver
    sudo apt-get --yes install nvidia-open

cuda-toolkit-version:
    nvcc --version

nccl-install-ubuntu-24:
    # https://developer.nvidia.com/nccl/nccl-download
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
    sudo dpkg --install cuda-keyring_1.1-1_all.deb
    sudo apt-get update
    sudo apt install libnccl2=2.27.6-1+cuda12.9 libnccl-dev=2.27.6-1+cuda12.9

nccl-version:
    ldconfig -p | grep nccl
    ls -l /lib/x86_64-linux-gnu/libnccl.so.2
