terraform-init:
	terraform init
terraform-update-lock-file:
	terraform init -upgrade
terraform-plan:
	terraform plan
terraform-apply:
	terraform apply -auto-approve
terraform-destroy:
	terraform destroy

terraform-get:
	terraform get
terraform-graph: # http://www.webgraphviz.com
	terraform graph
terraform-login:
	terraform login
terraform-validate:
	terraform validate
terraform-show:
	terraform show
terraform-state-list:
	terraform state list
terraform-output:
	terraform output
