argo-cd-app-create:
    argocd app create production-hm-litellm --file=argo-cd-manifests/hm-litellm-application.yaml

argo-cd-app-update:
    argocd app create production-hm-litellm --file=argo-cd-manifests/hm-litellm-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-litellm --yes
