create:
    argocd app create production-hm-litellm --file=argo-cd-manifests/hm-litellm.yaml

update:
    argocd app create production-hm-litellm --file=argo-cd-manifests/hm-litellm.yaml --upsert

delete:
    argocd app delete production-hm-litellm --yes
