opentofu-init:
    tofu init -backend=false -upgrade

opentofu-validate:
    tofu validate

opentofu-plan:
    tofu plan

opentofu-apply:
    # export TF_VAR_hm_postgres_bootstrap_user_password=xxx
    tofu apply
