[package]
name = "agent"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "=1.0.104"
arc-swap = "=1.9.2"
axum = "=0.8.9"
fluss-rs = "=0.1.0"
futures-util = "=0.3.34"
rig = "=0.41.0"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
thiserror = "=2.0.20"
tokio = { version = "=1.53.1", features = ["full"] }
