create:
    argocd app create production-hm-metrics-server --file=argo-cd-manifests/hm-metrics-server-application.yaml

update:
    argocd app create production-hm-metrics-server --file=argo-cd-manifests/hm-metrics-server-application.yaml --upsert

delete:
    argocd app delete production-hm-metrics-server --yes
