---
apiVersion: batch/v1
kind: Job
metadata:
  name: seatunnel-job
  namespace: seatunnel
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: docker.io/curlimages/curl:8.19.0
          command:
            - sh
            - -c
            - 'until curl --silent --fail http://postgres-postgresql:5432 || true; do sleep 2; done'
      containers:
        - name: seatunnel-job-runner
          image: docker.io/apache/seatunnel:2.3.9
          command:
            - /opt/seatunnel/bin/seatunnel.sh
            - -e
            - local
            - --config
            - /opt/seatunnel/config/postgres-to-paimon.conf
          volumeMounts:
            - name: config-volume
              mountPath: /opt/seatunnel/config/postgres-to-paimon.conf
              subPath: postgres-to-paimon.conf
      volumes:
        - name: config-volume
          configMap:
            name: seatunnel-job-config
