update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

download-model:
    hf download Qwen/Qwen2.5-0.5B-Instruct

launch-server:
    uv run poe launch-server

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
