vim:
    vim file.txt

quit:
    :q!

save-and-quit:
    :wq

insert:
    i

append:
    a

left:
    h

right:
    l

up:
    k

down:
    j

undo:
    u

jump-to-the-start-of-the-line:
    0

jump-to-the-end-of-the-line:
    $
