create:
    argocd app create production-hm-akhq --file=argo-cd-manifests/hm-akhq-application.yaml

update:
    argocd app create production-hm-akhq --file=argo-cd-manifests/hm-akhq-application.yaml --upsert

delete:
    argocd app delete production-hm-akhq --yes
