seal-secret:
    cat secrets/hm-airbyte-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/hm-airbyte-secret.yaml
