poetry-env-use:
	poetry env use python3.11
poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install --no-root

poetry-run-dev:
	poetry run poe dev

xxhash-install:
	brew install xxhash
xxhash-xxh32:
	xxh32sum file.txt
xxhash-xxh64:
	xxh64sum file.txt
xxhash-xxh128:
	xxh128sum file.txt
