create:
    argocd app create production-hm-qdrant --file=argo-cd-manifests/hm-qdrant-application.yaml

update:
    argocd app create production-hm-qdrant --file=argo-cd-manifests/hm-qdrant-application.yaml --upsert

delete:
    argocd app delete production-hm-qdrant --yes
