---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: hm-recording-report
spec:
  selector:
    app: api-server
  ports:
    - name: http
      port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: hm-recording-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: api-server
          ports:
            - containerPort: 8085
          env:
            - name: TEMPORAL_SERVER_URL
              value: http://temporal-frontend.hm-temporal.svc.cluster.local:7233
            - name: TEMPORAL_NAMESPACE
              value: recording-report
          readinessProbe:
            httpGet:
              path: /
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
