# https://huggingface.co/ggerganov/whisper.cpp/tree/main

MODEL_PATH := "models/ggml-tiny.en.bin"
AUDIO_PATH := "data/audio.flac"

install:
    brew install whisper-cpp

transcribe:
    whisper-cli --model "{{ MODEL_PATH }}" --file "{{ AUDIO_PATH }}" --output-txt
    whisper-cli --model "{{ MODEL_PATH }}" --file "{{ AUDIO_PATH }}" --output-json
    whisper-cli --model "{{ MODEL_PATH }}" --file "{{ AUDIO_PATH }}" --output-json-full
