create:
    argocd app create production-hm-caddy-ingress-controller --file=argo-cd-manifests/hm-caddy-ingress-controller-application.yaml

update:
    argocd app create production-hm-caddy-ingress-controller --file=argo-cd-manifests/hm-caddy-ingress-controller-application.yaml --upsert

delete:
    argocd app delete production-hm-caddy-ingress-controller --yes
