set-up:
    ./scripts/set_up.sh

dev:
    rtl_airband -f -c config/airband.conf

icecast:
    icecast -c icecast.xml
    # http://localhost:8000/ksjc-atis.mp3
    # http://localhost:8000/ksjc-ground.mp3
    # http://localhost:8000/ksjc-tower.mp3
