---
apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: livekit
spec:
  type: NodePort
  selector:
    app: livekit
  ports:
    - name: http
      port: 7880
    - name: rtc-tcp
      port: 7881
      protocol: TCP
      nodePort: 30881
    - name: rtc-udp
      port: 7882
      protocol: UDP
      nodePort: 30882
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit
  namespace: livekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit
  template:
    metadata:
      labels:
        app: livekit
    spec:
      enableServiceLinks: false
      containers:
        - name: livekit
          image: docker.io/livekit/livekit-server:v1.11.0
          args: ["--config", "/etc/livekit/livekit.yaml"]
          ports:
            - containerPort: 7880
            - containerPort: 7881
              protocol: TCP
            - containerPort: 7882
              protocol: UDP
          volumeMounts:
            - name: livekit-config
              mountPath: /etc/livekit/livekit.yaml
              subPath: livekit.yaml
              readOnly: true
      volumes:
        - name: livekit-config
          configMap:
            name: livekit-config
