pull-model:
    ollama pull qwen3:32b-q4_K_M

run-model:
    ollama run qwen3:32b-q4_K_M

stop-model:
    ollama stop qwen3:32b-q4_K_M

delete-model:
    ollama rm qwen3:32b-q4_K_M

list-models:
    ollama list

list-running-models:
    ollama ps
