sealed-secrets-seal:
    cat secrets/hm-ray-cluster-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=hm-sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/hm-ray-cluster-secret.yaml

argo-cd-app-create:
    argocd app create production-hm-ray-cluster --file=argo-cd-manifests/hm-ray-cluster-application.yaml

argo-cd-app-update:
    argocd app create production-hm-ray-cluster --file=argo-cd-manifests/hm-ray-cluster-application.yaml --upsert

ray-cluster-delete:
    kubectl delete raycluster hm-ray-cluster --namespace=production-hm-ray-cluster

argo-cd-app-delete:
    argocd app delete production-hm-ray-cluster --yes
