argo-cd-app-create:
    argocd app create production-hm-ray-cluster --file=argo-cd-manifests/hm-ray-cluster-application.yaml

argo-cd-app-update:
    argocd app create production-hm-ray-cluster --file=argo-cd-manifests/hm-ray-cluster-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-ray-cluster --yes
