argo-cd-app-create:
    argocd app create production-hm-keda --file=argo-cd-manifests/hm-keda-application.yaml

argo-cd-app-update:
    argocd app create production-hm-keda --file=argo-cd-manifests/hm-keda-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-keda --yes
