update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    AWS_ACCESS_KEY_ID=minio_user \
    AWS_SECRET_ACCESS_KEY=minio_passw0rd \
    METAFLOW_SERVICE_URL=http://localhost:8080 \
    METAFLOW_DATASTORE_SYSROOT_S3=s3://metaflow/ \
    METAFLOW_S3_ENDPOINT_URL=http://localhost:9000 \
    METAFLOW_DEFAULT_DATASTORE=s3 \
    METAFLOW_DEFAULT_METADATA=service \
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
