update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

stream-create:
    nats stream add --config=FIRE_AUDIO_STREAMS.json

stream-delete:
    nats stream delete FIRE_AUDIO_STREAMS --force

stream-info:
    nats stream info FIRE_AUDIO_STREAMS
