# Host
set-up-ssh:
	ssh-keygen -t ed25519
	ssh-copy-id -i ~/.ssh/id_ed25519.pub parallels@10.211.55.4

# Ubuntu
ssh:
	ssh parallels@10.211.55.4
apt-update:
	sudo apt update
apt-install:
	sudo apt --yes xxx
