data-manager-export-parquet:
	"C:\Program Files\IADS\DataManager\IadsDataManager.exe" /hide /DataExport C:\Users\Public\Documents\run\pfConfig Parquet "AW0001X,AW0005X,AW0007X|\ParquetCompressionType=ZSTD\ParquetZSTDCompressionLevel=19" 300:10:00:00.000 300:10:50:00.000 C:\Users\Public\Documents\data.parquet
