create:
    argocd app create production-hm-traefik --file=argo-cd-manifests/hm-traefik-application.yaml

update:
    argocd app create production-hm-traefik --file=argo-cd-manifests/hm-traefik-application.yaml --upsert

delete:
    argocd app delete production-hm-traefik --yes
