update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

set-up:
    sudo apt-get update
    sudo apt-get install --yes poppler-utils ttf-mscorefonts-installer msttcorefonts fonts-crosextra-caladea fonts-crosextra-carlito gsfonts lcdf-typetools

download-sample-pdf:
    curl --silent --fail --show-error --location --output file.pdf https://olmocr.allenai.org/papers/olmocr_3pg_sample.pdf

convert-pdf-to-markdown:
    uv run python -m olmocr.pipeline ./localworkspace --markdown --pdfs file.pdf
