argo-cd-project-create:
    argocd proj create production-hm --file

argo-cd-project-delete:
    argocd proj delete production-hm

argo-cd-repo-add:
    argocd repo add git@github.com:hongbo-miao/hongbomiao.com.git --ssh-private-key-path="$HOME/.ssh/hm_argo_cd_id_ed25519" --project=production-hm --upsert

argo-cd-repo-remove:
    argocd repo rm git@github.com:hongbo-miao/hongbomiao.com.git
