create-project:
    argocd proj create production-hm --file

delete-project:
    argocd proj delete production-hm

add-repository:
    argocd repo add git@github.com:hongbo-miao/hongbomiao.com.git --ssh-private-key-path="$HOME/.ssh/hm_argo_cd_id_ed25519" --project=production-hm --upsert

remove-repository:
    argocd repo rm git@github.com:hongbo-miao/hongbomiao.com.git
