update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

set-up:
    uv run poe set-up

verify:
    uv run poe verify

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
