uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

set-up:
    uv run poe set-up

verify:
    uv run poe verify

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
