docker-compose-up:
    docker compose --file=docker-compose.development.yaml up --detach --build

docker-compose-stop:
    docker compose --file=docker-compose.development.yaml stop

docker-compose-down:
    docker compose --file=docker-compose.development.yaml down --volumes

docker-compose-restart:
    docker compose --file=docker-compose.development.yaml down --volumes
    docker compose --file=docker-compose.development.yaml up --detach --build

list-security-associations:
    docker compose --file=docker-compose.development.yaml exec on-premises-gateway swanctl --list-sas

test-tunnel:
    docker compose --file=docker-compose.development.yaml exec on-premises-server ping -c 3 10.20.0.100

show-encrypted-packets:
    docker compose --file=docker-compose.development.yaml exec cloud-gateway tcpdump -i any -c 10 udp port 4500
