update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

build:
    uv run poe build

subscribe:
    uv run poe subscribe

publish:
    uv run poe publish

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

rti-convert:
    rtiddsgen -convertToXml hm_message.idl -d .
