create:
    argocd app create production-hm-starrocks-operator --file=argo-cd-manifests/hm-starrocks-operator-application.yaml

update:
    argocd app create production-hm-starrocks-operator --file=argo-cd-manifests/hm-starrocks-operator-application.yaml --upsert

delete:
    argocd app delete production-hm-starrocks-operator --yes
