services:
  nats-server:
    image: docker.io/library/nats:2.12.6-alpine3.22
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-server/nats-server.conf:/etc/nats/nats-server.conf
    command: ["--config", "/etc/nats/nats-server.conf"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8222/healthz"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s

  stream-initialize:
    image: docker.io/natsio/nats-box:0.19.3-nonroot
    depends_on:
      nats-server:
        condition: service_healthy
    volumes:
      - ./nats-server/SENSOR_TELEMETRY_STREAMS.json:/etc/nats/SENSOR_TELEMETRY_STREAMS.json
    entrypoint: >
      sh -c "nats stream add --config=/etc/nats/SENSOR_TELEMETRY_STREAMS.json --server=nats://nats-server:4222"
    restart: "no"

  publisher:
    build:
      context: .
      dockerfile: telemetry-stream-publisher/Dockerfile
    depends_on:
      stream-initialize:
        condition: service_completed_successfully
    environment:
      - NATS_URL=nats://nats-server:4222
    deploy:
      replicas: 3

  subscriber:
    build:
      context: .
      dockerfile: telemetry-stream-subscriber/Dockerfile
    depends_on:
      stream-initialize:
        condition: service_completed_successfully
    environment:
      - NATS_URL=nats://nats-server:4222
      - TOTAL_PARTITION_COUNT=2
    deploy:
      replicas: 2
