apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    # https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 81
        protocol: TCP
      - containerPort: 443
        hostPort: 444
        protocol: TCP
    extraMounts:
      - hostPath: ./kubernetes/data
        containerPath: /data
        readOnly: true
