update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

dbt-run:
    uv run poe dbt-run

dbt-test:
    uv run poe dbt-test
