update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

dbt-run:
    uv run poe dbt-run

dbt-test:
    uv run poe dbt-test
