uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage

uv-run-dbt-run:
    uv run poe dbt-run

uv-run-dbt-test:
    uv run poe dbt-test
