sky-launch:
    uv run sky launch experiment.sky.yaml --cluster=experiment-cluster

sky-stop:
    uv run sky stop experiment-cluster

sky-terminate:
    uv run sky down experiment-cluster

sky-ssh:
    uv run ssh experiment-cluster

sky-status:
    uv run sky status experiment-cluster
