install:
    sudo snap install zellij --classic

session-list:
    zellij list-sessions

session-new:
    zellij --session=my-session

session-attach:
    zellij attach my-session

session-detach:
    # ctrl + o, d
