sealed-secrets-seal:
    cat secrets/hm-ray-cluster-secret.unsealed.yaml | \
    kubeseal \
    	--controller-namespace=production-hm-sealed-secrets \
    	--controller-name=hm-sealed-secrets \
    	--format=yaml \
    	> kubernetes-manifests/hm-ray-cluster-secret.yaml

create:
    argocd app create production-hm-ray-cluster --file=argo-cd-manifests/hm-ray-cluster-application.yaml

update:
    argocd app create production-hm-ray-cluster --file=argo-cd-manifests/hm-ray-cluster-application.yaml --upsert

ray-cluster-delete:
    kubectl delete raycluster hm-ray-cluster --namespace=production-hm-ray-cluster

delete:
    argocd app delete production-hm-ray-cluster --yes
