argo-cd-app-create:
    argocd app create production-hm-qdrant --file=argo-cd-manifests/hm-qdrant-application.yaml

argo-cd-app-update:
    argocd app create production-hm-qdrant --file=argo-cd-manifests/hm-qdrant-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-qdrant --yes
