opentofu-init:
    tofu init -backend=false -upgrade

opentofu-validate:
    tofu validate

opentofu-plan:
    tofu plan

opentofu-apply:
    # argocd login localhost:31026 --username=admin --insecure
    tofu apply
