initialize:
    tofu init -backend=false -upgrade

plan:
    tofu plan

apply:
    # argocd login localhost:31026 --username=admin --insecure
    tofu apply

static-type-check-opentofu:
    tofu validate
