update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

export-yolo-to-onnx:
    uv run yolo export model=yolo12m.pt format=onnx

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
