vagrant-install:
    brew install --cask virtualbox
    brew install --cask vagrant
    brew install --cask vagrant-manager

vagrant-status:
    vagrant status

vagrant-ssh:
    vagrant ssh

vagrant-init:
    vagrant init ubuntu/jammy64

vagrant-up:
    vagrant up

vagrant-suspend:
    vagrant suspend

vagrant-halt:
    vagrant halt

vagrant-destroy:
    vagrant destroy --force

vagrant-box-list:
    vagrant box list

vagrant-box-outdated:
    vagrant box outdated

vagrant-box-update:
    vagrant box update

vagrant-box-add:
    vagrant box add ubuntu/jammy64

vagrant-box-remove:
    vagrant box remove ubuntu/jammy64

vagrant-box-help:
    vagrant help box

vagrant-plugin-list:
    vagrant plugin list

vagrant-plugin-install:
    vagrant plugin install vagrant-vbguest

vagrant-plugin-uninstall:
    vagrant plugin uninstall vagrant-vbguest

vagrant-plugin-help:
    vagrant help plugin
