install:
    brew install --cask virtualbox
    brew install --cask vagrant
    brew install --cask vagrant-manager

status:
    vagrant status

ssh:
    vagrant ssh

initialize:
    vagrant init ubuntu/jammy64

up:
    vagrant up

suspend:
    vagrant suspend

halt:
    vagrant halt

destroy:
    vagrant destroy --force

box-list:
    vagrant box list

box-outdated:
    vagrant box outdated

box-update:
    vagrant box update

box-add:
    vagrant box add ubuntu/jammy64

box-remove:
    vagrant box remove ubuntu/jammy64

box-help:
    vagrant help box

plugin-list:
    vagrant plugin list

plugin-install:
    vagrant plugin install vagrant-vbguest

plugin-uninstall:
    vagrant plugin uninstall vagrant-vbguest

plugin-help:
    vagrant help plugin
