uv-install-python:
	uv python install
uv-update-lock-file:
	uv lock
uv-install-dependencies:
	uv sync --dev

uv-run-deploy:
	uv run poe deploy
uv-run-undeploy:
	uv run poe undeploy
uv-run-test:
	uv run poe test
uv-run-test-coverage:
	uv run poe test-coverage
