install-toolchain:
    rustup install

update:
    cargo update

check:
    cargo check

test:
    cargo test --all-features

lint-rust-clippy:
    cargo clippy

lint-rust-clippy-fix:
    cargo clippy --fix --allow-dirty --allow-staged

lint-rust-rustfmt:
    cargo fmt --all -- --check

lint-rust-rustfmt-fix:
    cargo fmt --all

dev:
    ENVIRONMENT=development cargo run --release
    # http://localhost:3000

smoke-test:
    ENVIRONMENT=test cargo run --release
