komiser-install:
	brew tap tailwarden/komiser
	brew install komiser
komiser-start:
	# http://localhost:34552
	komiser start \
		--telemetry=false \
		--regions=us-west-2 \
		--regions=us-east-1 \
		--port=34552
