argo-cd-app-create:
	argocd app create hm-vertical-pod-autoscaler --file=argo-cd-manifests/hm-vertical-pod-autoscaler.yaml
argo-cd-app-update:
	argocd app create hm-vertical-pod-autoscaler --file=argo-cd-manifests/hm-vertical-pod-autoscaler.yaml --upsert
