# https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/values.yaml
---
dashboard:
  flags:
    on-by-default: true
  replicaCount: 3
  nodeSelector:
    environment: production
  tolerations:
    - key: environment
      operator: Equal
      value: production
      effect: NoSchedule
  resources:
    requests:
      cpu: 20m
      memory: 30Mi
    limits:
      memory: 300Mi
controller:
  flags:
    on-by-default: true
  nodeSelector:
    environment: production
  tolerations:
    - key: environment
      operator: Equal
      value: production
      effect: NoSchedule
  resources:
    requests:
      cpu: 1200m
      memory: 100Mi
    limits:
      memory: 630Mi
