uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

sky-api-sign-in:
    uv run sky api login --endpoint=https://skypilot:xxx@skypilot.hongbomiao.com

sky-check:
    uv run sky check

sky-check-runpod:
    uv run sky check runpod --verbose

sky-status:
    uv run sky status

sky-launch:
    uv run sky launch skypilot.yaml \
        --cluster=hm-skypilot-cluster \
        --idle-minutes-to-autostop=10

sky-stop:
    uv run sky stop hm-skypilot-cluster --yes

sky-terminate:
    uv run sky down hm-skypilot-cluster --yes

sky-ssh:
    uv run ssh hm-skypilot-cluster

sky-show-gpus:
    uv run sky show-gpus

sky-show-gpus-price:
    uv run sky show-gpus --all
    uv run sky show-gpus --all --cloud=aws --region=us-west-2
    uv run sky show-gpus A100-80GB:8
