uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

sky-api-sign-in:
    uv run sky api login --endpoint=https://skypilot:xxx@skypilot.hongbomiao.com

sky-check:
    uv run sky check
    uv run sky check runpod --verbose

sky-show-gpus:
    uv run sky show-gpus

sky-show-gpus-price:
    uv run sky show-gpus --all
    uv run sky show-gpus A100-80GB:8
    # AWS
    uv run sky show-gpus --infra=aws/us-west-2 --all
    # Runpod
    uv run sky show-gpus --infra=runpod --all
    uv run sky show-gpus --infra=runpod L4:2
    # Vast
    uv run sky show-gpus --infra=vast --all
