initialize:
    tofu init
    tofu init -upgrade
    tofu init -reconfigure
    tofu init -backend=false

plan:
    tofu plan
    tofu plan -parallelism=8

apply:
    tofu apply
    tofu apply -auto-approve
    tofu apply -parallelism=8

refresh:
    tofu refresh

destroy:
    tofu destroy

get:
    tofu get

graph:
    tofu graph

sign-in:
    tofu login

show:
    tofu show

state-list:
    tofu state list

output:
    tofu output

console:
    tofu console
    # substr(module.snowflake_development_hm_kafka_db_product_read_write_user_rsa_key.public_key_pem, 27, 747)
