create:
    argocd app create production-hm-velero --file=argo-cd-manifests/hm-velero-application.yaml

update:
    argocd app create production-hm-velero --file=argo-cd-manifests/hm-velero-application.yaml --upsert

delete:
    argocd app delete production-hm-velero --yes
