---
apiVersion: v1
kind: Service
metadata:
  name: grpc-pulsar-bridge
  namespace: audio-stream
spec:
  selector:
    app: grpc-pulsar-bridge
  ports:
    - name: grpc
      port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-pulsar-bridge
  namespace: audio-stream
spec:
  replicas: 4
  selector:
    matchLabels:
      app: grpc-pulsar-bridge
  template:
    metadata:
      labels:
        app: grpc-pulsar-bridge
    spec:
      containers:
        - name: grpc-pulsar-bridge
          image: grpc-pulsar-bridge
          ports:
            - containerPort: 50051
          env:
            - name: ENVIRONMENT
              value: development
