poetry-env-use:
	poetry env use python3.10
poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install --no-root

poetry-run-dbt-run:
	poetry run poe dbt-run
poetry-run-dbt-test:
	poetry run poe dbt-test
