poetry-env-use:
	poetry env use python3.11
poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install --no-root

poetry-run-test:
	poetry run poe test
poetry-run-test-coverage:
	poetry run poe test-coverage

poetry-run-dbt-run:
	poetry run poe dbt-run
poetry-run-dbt-test:
	poetry run poe dbt-test
