amazon-ec2-spot-fleet-requests-describe:
	aws ec2 describe-spot-fleet-requests --spot-fleet-request-ids=sfr-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
amazon-ec2-spot-fleet-requests-cancel:
	aws ec2 cancel-spot-fleet-requests --spot-fleet-request-ids=sfr-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --terminate-instances
