docker-build:
    cd ../.. && \
    docker build --file=security/hm-opal-client/Dockerfile --tag=ghcr.io/hongbo-miao/hm-opal-client:latest .

docker-push:
    docker push ghcr.io/hongbo-miao/hm-opal-client:latest
