poetry-env-use:
	poetry env use python3.12
poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install

poetry-run-dev:
	poetry run poe dev
poetry-run-test:
	poetry run poe test
poetry-run-test-coverage:
	poetry run poe test-coverage

curl-download-dog:
	curl --silent --fail --show-error --location --output data/dog.jpg https://i.ibb.co/bLvrvRV/shiba-inu-dog.jpg
