argo-cd-app-create:
    argocd app create production-hm-grafana --file=argo-cd-manifests/hm-grafana-application.yaml

argo-cd-app-update:
    argocd app create production-hm-grafana --file=argo-cd-manifests/hm-grafana-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-grafana --yes
