create:
    argocd app create production-hm-loki --file=argo-cd-manifests/hm-loki-application.yaml

update:
    argocd app create production-hm-loki --file=argo-cd-manifests/hm-loki-application.yaml --upsert

delete:
    argocd app delete production-hm-loki --yes
