poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install --no-root
poetry-run-generate-dashboard:
	poetry run poe generate-dashboard
poetry-run-upload-dashboard:
	poetry run poe upload-dashboard
