poetry-lock:
	poetry lock --no-update
poetry-install:
	poetry install
poetry-add:
	poetry add xxx
poetry-add-dev:
	poetry add xxx --group=dev
poetry-run-generate-dashboard:
	poetry run poe generate-dashboard
poetry-run-upload-dashboard:
	poetry run poe upload-dashboard
