# Amazon EMR
emr-cluster-create:
	aws emr create-cluster xxx
emr-cluster-list:
	aws emr list-clusters
emr-cluster-describe:
	aws emr describe-cluster --cluster-id=xxx
emr-cluster-terminate:
	aws emr terminate-clusters --cluster-ids=xxx

# Amazon MSK
msk-cluster-list:
	aws kafka list-clusters
msk-cluster-describe:
	aws kafka describe-cluster --cluster-arn=arn:aws:kafka:us-west-2:xxx
