vagrant-install:
	brew install --cask virtualbox
	brew install --cask vagrant
	brew install --cask vagrant-manager
vagrant-init:
	# vagrant init gusztavvargadr/windows-11
	vagrant init hbsmith/win11-arm
vagrant-up:
	vagrant up --provider=parallels
vagrant-destroy:
	vagrant destroy
