argo-cd-app-create:
    argocd app create production-hm-prometheus --file=argo-cd-manifests/hm-prometheus-application.yaml

argo-cd-app-update:
    argocd app create production-hm-prometheus --file=argo-cd-manifests/hm-prometheus-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-prometheus --yes
