vagrant-init:
    # vagrant init ubuntu/jammy64
    vagrant init bento/ubuntu-22.04-arm64

vagrant-up:
    vagrant up --provider=parallels

vagrant-suspend:
    vagrant suspend

vagrant-halt:
    vagrant halt

vagrant-destroy:
    vagrant destroy --force

vagrant-ssh:
    vagrant ssh

vagrant-status:
    vagrant status
