create:
    argocd app create production-hm-doris-operator --file=argo-cd-manifests/hm-doris-operator-application.yaml

update:
    argocd app create production-hm-doris-operator --file=argo-cd-manifests/hm-doris-operator-application.yaml --upsert

delete:
    argocd app delete production-hm-doris-operator --yes
