argo-cd-app-create:
    argocd app create production-hm-alloy --file=argo-cd-manifests/hm-alloy-application.yaml

argo-cd-app-update:
    argocd app create production-hm-alloy --file=argo-cd-manifests/hm-alloy-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-alloy --yes
