jetstream {}
leafnodes {
  remotes [
    {
      url: "nats-leaf://nats_leafnode_user:xxx@nats.hongbomiao.com:7422"
      deny_exports: [">"]
      deny_imports: [
        # https://github.com/nats-io/nats-server/blob/7755ef725c6cb20da951fa57e027b6824d87bdfa/server/stream.go#L2079
        # JetStream API
        "$JS.>"
        # JetStream cluster sync
        "$JSC.>"
        # NATS Raft Group consensus
        "$NRG.>"

        # https://github.com/nats-io/nats-server/blob/7755ef725c6cb20da951fa57e027b6824d87bdfa/server/jetstream_cluster.go#L6951
        # System account events
        "$SYS.>"

        # https://github.com/nats-io/nats.go/blob/a76c5a924a065983a028ec64da43670200adb750/nats.go#L4591
        # Request-reply inboxes
        "_INBOX.>"
      ]
      compression: fast
    }
  ]
}
