transcribe:
    whisper-cli --model models/ggml-tiny.en.bin --file data/audio.flac --output-txt
    whisper-cli --model models/ggml-tiny.en.bin --file data/audio.flac --output-json
    whisper-cli --model models/ggml-tiny.en.bin --file data/audio.flac --output-json-full
