create:
    argocd app create production-hm-redpanda-console --file=argo-cd-manifests/hm-redpanda-console-application.yaml

update:
    argocd app create production-hm-redpanda-console --file=argo-cd-manifests/hm-redpanda-console-application.yaml --upsert

delete:
    argocd app delete production-hm-redpanda-console --yes
