argo-cd-app-create:
    argocd app create production-hm-redpanda-console --file=argo-cd-manifests/hm-redpanda-console-application.yaml

argo-cd-app-update:
    argocd app create production-hm-redpanda-console --file=argo-cd-manifests/hm-redpanda-console-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-redpanda-console --yes
