argo-cd-app-create:
	argocd app create hm-goldilocks --file=argo-cd-manifests/hm-goldilocks.yaml
argo-cd-app-update:
	argocd app create hm-goldilocks --file=argo-cd-manifests/hm-goldilocks.yaml --upsert
