# KeyDB
keydb-start:
    keydb-server

keydb-stop:
    keydb-cli SHUTDOWN

keydb-cli:
    keydb-cli

keydb-cli-password:
    keydb-cli --pass passw0rd

keydb-cli-ping:
    keydb-cli PING

keydb-cli-keys:
    keydb-cli KEYS "*"

keydb-cli-set:
    keydb-cli SET hm-name Hongbo

keydb-cli-get:
    keydb-cli GET hm-name

keydb-cli-hmget:
    keydb-cli HMGET trending-twitter-hashtags field1 field2

keydb-benchmark:
    keydb-benchmark -a passw0rd

# KeyDB - multi-master
keydb-start-multi-master:
    keydb-server \
        --multi-master yes \
        --active-replica yes \
        --replicaof 192.168.2.58 6379 \
        --requirepass passw0rd \
        --masterauth passw0rd
    keydb-server \
        --multi-master yes \
        --active-replica yes \
        --replicaof 192.168.2.117 6379 \
        --requirepass passw0rd \
        --masterauth passw0rd

keydb-cli-lua-script-load:
    keydb-cli --pass passw0rd SCRIPT LOAD "$(cat greet.lua)"

# KeyDB - Docker
keydb-docker-build:
    cd ../.. && \
    rm -f /tmp/cid.txt && \
    docker create --cidfile=/tmp/cid.txt redislabs/redisgraph:latest && \
    docker cp $(cat /tmp/cid.txt):/usr/lib/redis/modules/redisgraph.so ./keydb/modules/ && \
    docker container rm $(cat /tmp/cid.txt) && \
    rm -f /tmp/cid.txt && \
    docker build --file=data-storage/keydb/Dockerfile --tag=ghcr.io/hongbo-miao/hm-keydb:latest .

keydb-docker-push:
    docker push ghcr.io/hongbo-miao/hm-keydb:latest

keydb-docker-run-multi-master:
    docker run \
        --detach \
        --name=hm-keydb \
        --publish=6379:6379 \
        ghcr.io/hongbo-miao/hm-keydb:latest \
        keydb-server \
            /etc/keydb/keydb.conf \
            --loadmodule /usr/lib/keydb/modules/redisgraph.so \
            --multi-master yes \
            --active-replica yes \
            --replicaof 192.168.2.58 6379 \
            --requirepass passw0rd \
            --masterauth passw0rd
    docker run \
        --detach \
        --name=hm-keydb \
        --publish=6379:6379 \
        ghcr.io/hongbo-miao/hm-keydb:latest \
        keydb-server \
            /etc/keydb/keydb.conf \
            --loadmodule /usr/lib/keydb/modules/redisgraph.so \
            --multi-master yes \
            --active-replica yes \
            --replicaof 192.168.2.117 6379 \
            --requirepass passw0rd \
            --masterauth passw0rd
