uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

mineru:
    uv run mineru --path=data --output=output --device=cuda:0

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
