update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

mineru:
    uv run mineru --path=data --output=output --device=cuda:0

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
