[package]
name = "firmware"
version = "1.0.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "=0.6.0", features = [
  "stm32f407vg",
  "time-driver-tim2",
  "memory-x",
  "exti",
] }
embassy-executor = { version = "=0.10.0", features = [
  "platform-cortex-m",
  "executor-thread",
] }
embassy-time = "=0.5.1"
cortex-m = { version = "=0.7.9", features = [
  "inline-asm",
  "critical-section-single-core",
] }
cortex-m-rt = "=0.7.6"
panic-halt = "=1.0.0"
heapless = "=0.8.0"

[profile.release]
debug = 2
opt-level = "s"
lto = true
