argo-cd-app-create:
    argocd app create production-hm-karpenter --file=argo-cd-manifests/hm-karpenter-application.yaml

argo-cd-app-update:
    argocd app create production-hm-karpenter --file=argo-cd-manifests/hm-karpenter-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-karpenter --yes

describe-ec2-node-class:
    kubectl describe ec2nodeclass production-hm-karpenter-node-class
