sealed-secrets-seal:
    cat secrets/hm-harbor-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=hm-sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/hm-harbor-secret.yaml

argo-cd-app-create:
    argocd app create production-hm-harbor --file=argo-cd-manifests/hm-harbor-application.yaml

argo-cd-app-update:
    argocd app create production-hm-harbor --file=argo-cd-manifests/hm-harbor-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-harbor --yes
