update-lock-file:
    npm install --package-lock-only

install-dependencies:
    npm install

install-playwright-browser:
    npx playwright install chromium --with-deps

end-to-end-test-8080:
    npm run end-to-end-test-8080

end-to-end-test-58136:
    npm run end-to-end-test-58136

end-to-end-test-ui-8080:
    npm run end-to-end-test-ui-8080

end-to-end-test-ui-58136:
    npm run end-to-end-test-ui-58136

end-to-end-test-report:
    npm run end-to-end-test-report

lint-javascript:
    npm run lint-javascript

lint-javascript-fix:
    npm run lint-javascript-fix

static-type-check-typescript:
    npm run static-type-check-typescript
