update-lock-file:
    npm install --package-lock-only

install-dependencies:
    npm install

install-playwright-browsers:
    npx playwright install --with-deps

test-playwright-gui-8080:
    npm run test-playwright-gui-8080

test-playwright-gui-58136:
    npm run test-playwright-gui-58136

test-playwright-headless-8080:
    npm run test-playwright-headless-8080

test-playwright-headless-58136:
    npm run test-playwright-headless-58136

lint-javascript:
    npm run lint-javascript

lint-javascript-fix:
    npm run lint-javascript-fix

static-type-check-typescript:
    npm run static-type-check-typescript
