uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

download-model:
    uv run poe download-model

launch-server:
    uv run poe launch-server

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
