argo-cd-app-create:
	argocd app create hm-cert-manager --file=argo-cd-manifests/hm-cert-manager.yaml
argo-cd-app-update:
	argocd app create hm-cert-manager --file=argo-cd-manifests/hm-cert-manager.yaml --upsert
