uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --extra=build
    uv sync --extra=build --extra=compile
    uv sync --extra=build --extra=compile --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

download-examples:
    uv run axolotl fetch examples

train:
    uv run axolotl train config/llama-3/lora-1b.yml
    uv run axolotl train config/llama-3/qlora-1b.yml
