run:
    docker run \
        --rm \
        --name=icecast2 \
        --publish=52231:8000 \
        --volume="$(pwd)/icecast.xml:/etc/icecast2/icecast.xml" \
        docker.io/pltnk/icecast2:latest

publish:
    ffmpeg \
        -re \
        -stream_loop -1 \
        -i data/audio-1.flac \
        -c:a libopus \
        -b:a 128k \
        -content_type audio/webm \
        -f webm \
        icecast://source:passw0rd1@localhost:52231/audio-1

subscribe:
    ffplay http://localhost:52231/audio-1
