amazon-sagemaker-create-notebook-instance:
	aws sagemaker create-notebook-instance \
		--notebook-instance-name=hm-sagemaker-notebook \
		--instance-type=ml.m5.xlarge \
		--role-arn=arn:aws:iam::xxxxxxxxxxxx:role/service-role/xxx \
		--platform-identifier=notebook-al2-v2 \
		--root-access=Enabled
