update-lock-file:
    npm install --package-lock-only

install-dependencies:
    npm install

test-cypress-gui-8080:
    npm run test-cypress-gui-8080

test-cypress-gui-58136:
    npm run test-cypress-gui-58136

test-cypress-headless-8080:
    npm run test-cypress-headless-8080

test-cypress-headless-58136:
    npm run test-cypress-headless-58136

lint-javascript:
    npm run lint-javascript

lint-javascript-fix:
    npm run lint-javascript-fix

static-type-check-typescript:
    npm run static-type-check-typescript
