argo-cd-app-create:
    argocd app create production-hm-nessie --file=argo-cd-manifests/hm-nessie-application.yaml

argo-cd-app-update:
    argocd app create production-hm-nessie --file=argo-cd-manifests/hm-nessie-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-nessie --yes
