update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

deploy:
    uv run poe deploy

undeploy:
    uv run poe undeploy

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
