confluent-kafka-install:
	brew install confluentinc/tap/cli

confluent-kafka-start:
	confluent local kafka start
confluent-kafka-stop:
	confluent local kafka stop

confluent-kafka-topic-list:
	confluent local kafka topic list
confluent-kafka-topic-create:
	confluent local kafka topic create purchases
