---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hm-prometheus-prefect-exporter-secret
  namespace: production-hm-prometheus-prefect-exporter
spec:
  encryptedData:
    auth-string: AgBVn2qgdUwCmLnQERnLQTgdC3XI1Xipsx8J8ldwiUTE/Hr/KBb7w5+SMYe74UzUbtQaCFMIqarQPX/d2gt/bPFOQ5TrdLOMPbtjCjBX93D0FulwQztsQkEoBFPNcWe2r9PtV6sASE20rjI9c2nXPonAgsagb3gq7creiZ0aG8vPrSktUbqRzyG4QfrZoYy+RsAXFgCjJEqHDA7jsKhq7DAW4Jm1DinfhY12ccJrvZZReS8M3ZFqZk/6la1td1bMzYIbyFSXIUHvYRl2D09fSVRHyOLtGY70KfIRq2u4evfItYaptsI7Q0lsES0z6jDjiRijMFEpvVvgwlaxmQ7+z7ycGvF8TLlzm1aACJ9qGfcetnC+DIgiPjUU79tUyA+W+sV9vQcX2zpaYkFpa+/LuPM89ygS8K6b5J0ci5wlnYjlGpdNK7sbNwupL97TQAKOF8NH93qAOncDHjMOA5JeYS3vc8aGkkk1G3ixSGYAdpMVKPHsQhwlbk+sjpsmFJ14+3kfCOfasTplMC388vvwHimqPXJqU8/Mh4R/++7OnimZxbygm+mJjoL7zJlal/2jGdZzcPDKuIN6VjZYIdH8PZ7roLP1ITKGiMpKKzGeRw18HL/BaOD0qYZHTYwyXfwDTp+yuZK+08FDxBle6audivkuhV78BnUIMC3len/ywIWk0XVw+nG1Oz8brpaMZ7XKXPm0iw+TsYpbDif3FXlM7QSw+w7a5krOE5zVP2iAk/JlKnzr8ht+C8e9On8xXAvt33l1It+UZoxAaw==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-prefect-exporter
        app.kubernetes.io/part-of: production-hm-prometheus-prefect-exporter
      name: hm-prometheus-prefect-exporter-secret
      namespace: production-hm-prometheus-prefect-exporter
