argo-cd-app-create:
	argocd app create hm-caddy-ingress-controller --file=argo-cd-manifests/hm-caddy-ingress-controller.yaml
argo-cd-app-update:
	argocd app create hm-caddy-ingress-controller --file=argo-cd-manifests/hm-caddy-ingress-controller.yaml --upsert
