openjdk-install:
	brew install openjdk@17

poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install
poetry-add:
	poetry add xxx
poetry-add-dev:
	poetry add xxx --group=dev

poetry-run-find-taxi-top-routes:
	poetry run poe find-taxi-top-routes
poetry-run-find-taxi-top-routes-sql:
	poetry run poe find-taxi-top-routes-sql
poetry-run-recommend-movie:
	poetry run poe recommend-movie
