brew-install:
	brew install openjdk@17

poetry-lock:
	poetry lock --no-update
poetry-install:
	poetry install
poetry-add:
	poetry add xxx
poetry-add-dev:
	poetry add xxx --group=dev

poetry-run-get-taxi-statistics:
	poetry run poe get-taxi-statistics
poetry-run-get-taxi-statistics-sql:
	poetry run poe get-taxi-statistics-sql
