create:
    argocd app create production-hm-keda --file=argo-cd-manifests/hm-keda-application.yaml

update:
    argocd app create production-hm-keda --file=argo-cd-manifests/hm-keda-application.yaml --upsert

delete:
    argocd app delete production-hm-keda --yes
