---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hm-harbor-valkey-secret
  namespace: production-hm-harbor-valkey
spec:
  encryptedData:
    VALKEY_PASSWORD: AgCTRbtRyLRuHzPbRkAVq4/WXCwH3SfE7OqIqOOKScHUFgex26YXw3/OA5QlNxs3MwvRx18ZiqPDgR85NxNOCqkBmnpnT5hQADpTslXf4HcEPtnaqNR3j6JS1LGcIpqeIPYFBwm9jOzEtVF9WcrXuA4PLYyX6DiWFbBPvVczKhuV1ay/dMS8kXX6UJjcsqU5zKAtGB3jUhE+oq+/lc4EEgnM0AUd/MlG4zlEpeCm6GahMf5oUofmjsLJZ8ogkwcJaefmgUJlf/vmdYXQbWATSEFh2IvaO9TnpHLV6B9MfhL2wcxhVR9HfH5YAphiFsatn5QbX+9XN0nlX734BqXSnWWakfh0tonJxlwWhz+07eborYeTZfx/yf1XSVXj08kU/gPWIXsCLhj7xjF61ostiWsMPcY3WbtsUCfyak+w2fC57v1XCXoEypvUUyoaNWU4pgKl5XRmEQ/fnkYIFyH9BtitXqxrAFzD6SgwtV5S1fqDxp6FaDdh1kuTUQOlSTke7a5aWXCI3MJcFXjL+lREHRAR+AkHDvUnbkJvIYes/6eGfUkjDTEv1JcnfKbnT0ULlkXrOWJO/4bdQpDjh2kV6WsVLRN+aIbLe37T/kt8FC1lwBxvyjH7PxFoYKsnmYIuUminn02HW9+GkgdAXaMqaeJ0L35zglz8FnpidldvR5qsDb0kSVQqvet2onX4UTS+uxu9wb1w/kII41zm6s41vwtEu7bxy0Dn92hD00wvXvJrS9DNEJTeX66WC03V996CUA7lGQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor-valkey
        app.kubernetes.io/part-of: production-hm-harbor-valkey
      name: hm-harbor-valkey-secret
      namespace: production-hm-harbor-valkey
