seal-secret:
    cat secrets/hm-pyroscope-secret.unsealed.yaml | \
    kubeseal \
        --cert=https://sealed-secrets.hongbomiao.com/v1/cert.pem \
        --format=yaml \
        > kubernetes-manifests/hm-pyroscope-secret.yaml
