create:
    argocd app create production-hm-karpenter --file=argo-cd-manifests/hm-karpenter-application.yaml

update:
    argocd app create production-hm-karpenter --file=argo-cd-manifests/hm-karpenter-application.yaml --upsert

delete:
    argocd app delete production-hm-karpenter --yes

describe-ec2-node-class:
    kubectl describe ec2nodeclass production-hm-karpenter-node-class
