argo-cd-app-create:
    argocd app create production-hm-valkey --file=argo-cd-manifests/hm-valkey-application.yaml

argo-cd-app-update:
    argocd app create production-hm-valkey --file=argo-cd-manifests/hm-valkey-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-valkey --yes
