test:
    mvn test

build:
    mvn clean package

# SWIM
dev: build
    ENVIRONMENT=development java -jar target/swim-consumer-0.1.jar

serve: build
    ENVIRONMENT=production java -jar target/swim-consumer-0.1.jar
