create:
    argocd app create production-hm-doris --file=argo-cd-manifests/hm-doris-application.yaml

update:
    argocd app create production-hm-doris --file=argo-cd-manifests/hm-doris-application.yaml --upsert

delete:
    argocd app delete production-hm-doris --yes
