seal-secret:
    cat secrets/object-storage-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/object-storage-secret.yaml
