seal-secret:
    cat secrets/object-storage-secret.unsealed.yaml | \
    kubeseal \
        --cert=https://sealed-secrets.hongbomiao.com/v1/cert.pem \
        --format=yaml \
        > kubernetes-manifests/object-storage-secret.yaml
