uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --extra=build
    uv sync --extra=build --extra=compile
    uv sync --extra=build --extra=compile --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
