update-lock-file:
    uv lock

install-dependencies:
    uv sync --extra=build
    uv sync --extra=build --extra=compile
    uv sync --extra=build --extra=compile --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
