---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hm-vllm-engine
  namespace: production-hm-vllm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: serving-engine
      app.kubernetes.io/part-of: vllm-stack
  endpoints:
    - port: service-port
      path: /metrics
