update-lock-file:
    npm install --package-lock-only

install-dependencies:
    npm install

dev:
    npm run dev

dev-grafana:
    npm run dev-grafana

test:
    npm run test

lint-javascript:
    npm run lint-javascript

lint-javascript-fix:
    npm run lint-javascript-fix

static-type-check-typescript:
    npm run static-type-check-typescript
