update-lock-file:
    npm install --package-lock-only

install-dependencies:
    npm install

install-playwright-browsers:
    npx playwright install --with-deps

dev:
    npm run dev

dev-grafana:
    npm run dev-grafana

test:
    npm run test

end-to-end-test:
    npm run end-to-end-test

end-to-end-test-report:
    npm run end-to-end-test-report

lint-javascript:
    npm run lint-javascript

lint-javascript-fix:
    npm run lint-javascript-fix

static-type-check-typescript:
    npm run static-type-check-typescript
