create:
    argocd app create production-hm-cert-manager --file=argo-cd-manifests/hm-cert-manager-application.yaml

update:
    argocd app create production-hm-cert-manager --file=argo-cd-manifests/hm-cert-manager-application.yaml --upsert

delete:
    argocd app delete production-hm-cert-manager --yes
