argo-cd-app-create:
    argocd app create production-hm-doris --file=argo-cd-manifests/hm-doris-application.yaml

argo-cd-app-update:
    argocd app create production-hm-doris --file=argo-cd-manifests/hm-doris-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-doris --yes
