uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

hugging-face-sign-in:
    uv run poe hugging-face-sign-in

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
