# Maven
maven-install:
	mvn install
maven-compile:
	mvn compile
maven-test:
	mvn test
maven-verify:
	mvn verify
maven-package:
	mvn clean package

# Flink
flink-start:
	/usr/local/Cellar/apache-flink/1.13.1/libexec/bin/start-cluster.sh
flink-stop:
	/usr/local/Cellar/apache-flink/1.13.1/libexec/bin/stop-cluster.sh
