create:
    argocd app create production-hm-nessie --file=argo-cd-manifests/hm-nessie-application.yaml

update:
    argocd app create production-hm-nessie --file=argo-cd-manifests/hm-nessie-application.yaml --upsert

delete:
    argocd app delete production-hm-nessie --yes
