apiVersion: v1
kind: ConfigMap
metadata:
  name: api-go-grpc-configmap
  namespace: hm
data:
  grpc_port: "50051"
  open_census_agent_host: "collector.linkerd-jaeger"
  open_census_agent_port: "55678"
