apiVersion: v1
kind: ConfigMap
metadata:
  name: api-go-configmap
  namespace: hm
data:
  app_env: "production"
  port: "5000"
  grpc_host: "api-go-grpc-service.hm"
  grpc_port: "50051"
  open_census_agent_host: "collector.linkerd-jaeger"
  jaeger_url: "http://collector.linkerd-jaeger:14268/api/traces"
  open_census_agent_port: "55678"
  opal_server_url: "http://opal-server-service.hm:7002"
  opal_log_module_exclude_list: "[]"
  opal_inline_opa_log_format: "http"
