apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go-deployment
  namespace: hm
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-go
  template:
    metadata:
      labels:
        component: api-go
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: api-go
          image: hongbomiao/hm-api-go:latest
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: app_env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: port
            - name: GRPC_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: grpc_host
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: grpc_port
            - name: OPEN_CENSUS_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: open_census_agent_host
            - name: OPEN_CENSUS_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: open_census_agent_port
            - name: JAEGER_URL
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: jaeger_url
          ports:
            - name: api-go
              protocol: TCP
              containerPort: 5000
        - name: opal-client
          image: authorizon/opal-client:0.1.9
          env:
            - name: OPAL_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: opal_server_url
            - name: OPAL_LOG_MODULE_EXCLUDE_LIST
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: opal_log_module_exclude_list
            - name: OPAL_INLINE_OPA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: opal_inline_opa_config
            - name: OPAL_INLINE_OPA_LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: api-go-configmap
                  key: opal_inline_opa_log_format
          ports:
            - name: opal-client
              protocol: TCP
              containerPort: 7000
            - name: opa
              protocol: TCP
              containerPort: 8181
          volumeMounts:
            - mountPath: /home/opa
              name: opal-client-volume
              readOnly: true
      volumes:
        - name: opal-client-volume
          persistentVolumeClaim:
            claimName: opal-client-pvc
            readOnly: true
