apiVersion: v1
kind: Service
metadata:
  name: api-go-service
  namespace: hm
spec:
  type: LoadBalancer
  selector:
    component: api-go
  ports:
    - name: api-go
      protocol: TCP
      targetPort: api-go
      port: 5000
    - name: opal-client
      protocol: TCP
      targetPort: opal-client
      port: 7000
    - name: opa
      protocol: TCP
      targetPort: opa
      port: 8181
