apiVersion: v1
kind: PersistentVolume
metadata:
  name: opal-client-pv
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /opa
    type: DirectoryOrCreate
