apiVersion: v1
kind: Service
metadata:
  name: opal-broadcast-channel
  namespace: hm
spec:
  type: ClusterIP
  selector:
    component: opal-broadcast-channel
  ports:
    - name: pgsql
      protocol: TCP
      port: 5432
      targetPort: pgsql
