uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --extra=build
    uv sync --extra=build --extra=compile
    uv sync --extra=build --extra=compile --extra=paddlepaddle-gpu
    uv sync --extra=build --extra=compile --extra=paddlepaddle-gpu --dev

download-model:
    # https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_en.md#download-the-model-from-hugging-face    # https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_en.md#download-the-model-from-hugging-face
    uv pip install huggingface_hub
    wget --no-verbose --output-document=download_models_hf.py https://github.com/opendatalab/MinerU/raw/master/scripts/download_models_hf.py
    uv run python download_models_hf.py

uv-run-dev:
    uv run poe dev

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage
