conda-create:
	conda create --name=py396 python=3.9.6
conda-activate:
	conda activate py396
conda-env-list:
	conda env list
conda-env-remove:
	conda env remove --name=py396
conda-env-remove:
	conda install pytorch torchvision torchaudio --channel=pytorch
