initialize:
    tofu init -backend=false -upgrade

opentofu-plan:
    tofu plan

apply:
    # export HARBOR_USERNAME="admin"
    # export HARBOR_PASSWORD="xxx"
    tofu apply

static-type-check-opentofu:
    tofu validate
