create:
    argocd app create production-hm-tempo --file=argo-cd-manifests/hm-tempo-application.yaml

update:
    argocd app create production-hm-tempo --file=argo-cd-manifests/hm-tempo-application.yaml --upsert

delete:
    argocd app delete production-hm-tempo --yes
