create:
    argocd app create production-hm-prometheus --file=argo-cd-manifests/hm-prometheus-application.yaml

update:
    argocd app create production-hm-prometheus --file=argo-cd-manifests/hm-prometheus-application.yaml --upsert

delete:
    argocd app delete production-hm-prometheus --yes
