create:
    argocd app create production-hm-sealed-secrets --file=argo-cd-manifests/hm-sealed-secrets-application.yaml

update:
    argocd app create production-hm-sealed-secrets --file=argo-cd-manifests/hm-sealed-secrets-application.yaml --upsert

delete:
    argocd app delete production-hm-sealed-secrets --yes
