uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-build:
    uv run poe build

uv-run-subscribe:
    uv run poe subscribe

uv-run-publish:
    uv run poe publish

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage

rti-convert:
    rtiddsgen -convertToXml hm_message.idl -d .
