uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

build:
    uv run poe build

subscribe:
    uv run poe subscribe

publish:
    uv run poe publish

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

rti-convert:
    rtiddsgen -convertToXml hm_message.idl -d .
