# https://strimzi.io/docs/operators/latest/configuring#type-Kafka-reference
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: hm-mimir-kafka
spec:
  kafka:
    version: 4.2.0
    metadataVersion: "4.2"
    listeners:
      # https://github.com/grafana/mimir/issues/13366
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      num.partitions: 3
      log.retention.hours: 24
      # 500 GB
      log.retention.bytes: 500000000000
