argo-cd-app-create:
    argocd app create production-hm-starrocks --file=argo-cd-manifests/hm-starrocks-application.yaml

argo-cd-app-update:
    argocd app create production-hm-starrocks --file=argo-cd-manifests/hm-starrocks-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-starrocks --yes
