cargo-new:
	cargo new xxx
cargo-upgrade:
	cargo install cargo

cargo-run:
	cargo run
cargo-run-release:
	cargo run --release

cargo-fmt-check:
	cargo fmt --all -- --check
cargo-fmt-fix:
	cargo fmt --all
