install-toolchain:
    rustup install

clean:
    cargo clean

update:
    cargo update

check:
    cargo check

test:
    cargo test --all-features

set-up:
    mkcert -cert-file certificates/development.pem -key-file certificates/development-key.pem localhost 127.0.0.1 ::1
    docker run --publish=5432:5432 --name=hm-postgres --env=POSTGRES_PASSWORD=passw0rd --detach docker.io/supabase/postgres:17.6.1.040

dev:
    cargo run

lint-rust-clippy:
    cargo clippy

lint-rust-clippy-fix:
    cargo clippy --fix --allow-dirty --allow-staged

lint-rust-rustfmt:
    cargo fmt --all -- --check

lint-rust-rustfmt-fix:
    cargo fmt --all

docker-build:
    cd ../.. && \
    docker build --file=api/api-rust/Dockerfile --tag=ghcr.io/hongbo-miao/hm-api-rust:latest .

docker-push:
    docker push ghcr.io/hongbo-miao/hm-api-rust:latest

docker-run:
    docker run --publish=36147:36147 --name=hm-api-rust --rm ghcr.io/hongbo-miao/hm-api-rust:latest

brew-install-opencv:
    brew install opencv

listen-police-audio-stream:
    websocat --binary 'ws://localhost:36147/ws/police-audio-stream?police_stream_id=chicago_police' \
        | sox --type=raw --rate=16000 --encoding=signed --bits=16 --channels=1 - --default-device

listen-fire-audio-stream:
    websocat --binary 'ws://localhost:36147/ws/fire-audio-stream?fire_stream_id=lincoln_fire' \
        | perl -e 'while (read(STDIN, $len, 4)) { $n = unpack("V", $len); read(STDIN, $buf, $n); print $buf; }' \
        | sox --type=raw --rate=16000 --encoding=signed --bits=16 --channels=1 - --default-device
