---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hm-postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hm-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:18.4-trixie
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres_admin
            - name: POSTGRES_PASSWORD
              value: postgres_passw0rd
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: ["pg_isready", "--username=postgres_admin"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          emptyDir: {}
