create:
    argocd app create production-hm-goldilocks --file=argo-cd-manifests/hm-goldilocks-application.yaml

update:
    argocd app create production-hm-goldilocks --file=argo-cd-manifests/hm-goldilocks-application.yaml --upsert

delete:
    argocd app delete production-hm-goldilocks --yes
