prefect-server-start:
    prefect server start

prefect-agent-start:
    prefect agent start --work-queue=hm-local-queue

prefect-profile-ls:
    prefect profile ls

prefect-profile-use:
    prefect profile use default
    prefect profile use xxx

prefect-profile-create:
    prefect profile create xxx

prefect-profile-delete:
    prefect profile delete xxx

prefect-profile-inspect:
    prefect profile inspect xxx

prefect-queue-ls:
    prefect work-queue ls

prefect-queue-create:
    prefect work-queue create hm-local-queue

prefect-config-view:
    prefect config view

prefect-config-view-show-defaults:
    prefect config view --show-defaults

prefect-config-set:
    prefect config set PREFECT_API_URL=http://localhost:4200/api

# Prefect Cloud
prefect-cloud-login:
    prefect cloud login

prefect-cloud-workspace-set:
    prefect cloud workspace set --workspace=hongbo-miao/hongbomiao
