prefect-profile-view:
    cat ~/.prefect/profiles.toml

prefect-profile-create:
    uv run poe profile-create -- hm

prefect-profile-use:
    uv run poe profile-use -- hm

prefect-config-set:
    uv run poe config-set -- PREFECT_API_URL=https://prefect.hongbomiao.com/api

prefect-generate-kubernetes-base-job-template:
    uv run poe get-kubernetes-base-job-template > base-job-template.json
