# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/protos/production.iot.motor.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'src/protos/production.iot.motor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%src/protos/production.iot.motor.proto\x12\x0eproduction.iot\"\xa7\x02\n\x05Motor\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x19\n\x0ctimestamp_ns\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x19\n\x0ctemperature1\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x19\n\x0ctemperature2\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x19\n\x0ctemperature3\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x19\n\x0ctemperature4\x18\x06 \x01(\x01H\x05\x88\x01\x01\x12\x19\n\x0ctemperature5\x18\x07 \x01(\x01H\x06\x88\x01\x01\x42\x05\n\x03_idB\x0f\n\r_timestamp_nsB\x0f\n\r_temperature1B\x0f\n\r_temperature2B\x0f\n\r_temperature3B\x0f\n\r_temperature4B\x0f\n\r_temperature5b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.production.iot.motor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTOR']._serialized_start=58
  _globals['_MOTOR']._serialized_end=353
# @@protoc_insertion_point(module_scope)
