FROM harbor.hongbomiao.com/docker-hub-proxy-cache/burakince/mlflow:3.7.0
# https://mlflow-oidc.github.io/mlflow-oidc-auth/#/installation
RUN pip install --no-cache-dir 'mlflow-oidc-auth[full,caching-redis]==6.7.1'
