vagrant-init:
	# vagrant init generic/debian11
	vagrant init bento/debian-11.2-arm64
vagrant-up:
	vagrant up --provider=parallels
vagrant-suspend:
	vagrant suspend
vagrant-halt:
	vagrant halt
vagrant-destroy:
	vagrant destroy --force
vagrant-ssh:
	vagrant ssh
vagrant-status:
	vagrant status
