uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

feast-init:
    feast init driver_features

download-driver-stats:
    curl --silent --fail --show-error --location https://raw.githubusercontent.com/hongbo-miao/hm-driver-stats/main/driver_stats.parquet > features/data/driver_stats.parquet

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

inspect-raw-data:
    uv run poe inspect-raw-data

# Scan python files in the current directory for feature view/entity definitions, registers the objects, and deploys infrastructure.
feast-apply:
    uv run poe feast-apply

# Generate training data
generate-training-data:
    uv run poe generate-training-data

# Load features into your online store
materialize-features:
    uv run poe materialize-features

# Inspect materialized features
inspect-features:
    uv run poe inspect-features

# Fetch feature vectors for inference
fetch-features:
    uv run poe fetch-features

# Fetch feature vectors for inference by feature service
fetch-features-by-service:
    uv run poe fetch-features-by-service

feast-ui:
    uv run poe feast-ui
