global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['hm_opentelemetry_collector:9464']
