seal-secrets:
    cat secrets/hm-ray-cluster-valkey-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=hm-sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/hm-ray-cluster-valkey-secret.yaml
