uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage

helm-download-values:
    helm show values apache-airflow/airflow > values.yaml

helm-get-my-values:
    helm get values airflow --namespace=hm-airflow
