update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

helm-download-values:
    helm show values apache-airflow/airflow > values.yaml

helm-get-my-values:
    helm get values airflow --namespace=hm-airflow
