conda-create:
	conda create --name=hm-quantum python=3.9 --yes
conda-env-remove:
	conda env remove --name=hm-quantum
conda-activate:
	conda activate hm-quantum

run:
	/usr/local/anaconda3/envs/hm-quantum/bin/python main.py
