uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

# Ansible Galaxy
ansible-galaxy-install:
    uv run poe install

# Ansible Vault
encrypt-string:
    uv run ansible-vault encrypt_string 'xxx' \
    	--vault-password-file=~/.ansible_vault_pass

decrypt-string:
    echo '$ANSIBLE_VAULT;1.1;AES256 xxx' | tr -d ' ' | uv run ansible-vault decrypt && echo

deploy-hm-macos-group:
    uv run poe deploy-hm-macos-group \
    	--vault-password-file=~/.ansible_vault_pass

# Ansible
ansible-galaxy-update:
    uv run ansible-galaxy install --role-file=requirements.yml --force

ansible-galaxy-collection-list:
    uv run ansible-galaxy collection list

ansible-galaxy-collection-install:
    uv run ansible-galaxy collection install xxx

ansible-galaxy-collection-update:
    uv run ansible-galaxy collection install xxx --force

ansible-galaxy-role-list:
    uv run ansible-galaxy role list

ansible-galaxy-role-install:
    uv run ansible-galaxy install xxx

ansible-galaxy-role-update:
    uv run ansible-galaxy install xxx --force

ansible-doc-list:
    uv run ansible-doc --list

ansible-inventory-list:
    uv run ansible-inventory --inventory=inventory.yaml --list

ansible-inventory-graph:
    uv run ansible-inventory --inventory=inventory.yaml --graph

ansible-run-ping:
    uv run ansible hm_ubuntu_group --inventory=inventory.yaml --vault-password-file=~/.ansible_vault_pass --module-name=ping

ansible-run-show-system-info:
    uv run ansible hm_ubuntu_group --inventory=inventory.yaml --vault-password-file=~/.ansible_vault_pass --module-name=setup

ansible-run-uptime:
    uv run ansible hm_ubuntu_group --inventory=inventory.yaml --vault-password-file=~/.ansible_vault_pass --args=uptime

ansible-playbook-list-tags:
    uv run ansible-playbook hm_ubuntu_group/playbook.yml --list-tags

ansible-playbook-hm-macos-group:
    uv run ansible-playbook --inventory=inventory.yaml --vault-password-file=~/.ansible_vault_pass hm_macos_group/playbook.yml

ansible-playbook-hm-ubuntu-group:
    uv run ansible-playbook --inventory=inventory.yaml --vault-password-file=~/.ansible_vault_pass hm_ubuntu_group/playbook.yml

ansible-playbook-hm-windows-group:
    uv run ansible-playbook --inventory=inventory.yaml --vault-password-file=~/.ansible_vault_pass hm_windows_group/playbook.yml
