poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install
poetry-add:
	poetry add xxx
poetry-add-dev:
	poetry add xxx --group=dev

poetry-run-workflow-calculate:
	poetry run poe workflow-calculate
poetry-run-workflow-find-taxi-top-routes:
	poetry run poe workflow-find-taxi-top-routes
poetry-run-workflow-greet:
	poetry run poe workflow-greet

poetry-run-prefect-local:
	poetry run poe prefect-local
poetry-run-prefect-cloud-login:
	poetry run poe prefect-cloud-login -- --key=xxx
poetry-run-prefect-prefect-cloud-workspace-set:
	poetry run poe prefect-cloud-workspace-set

poetry-run-test:
	poetry run poe test
poetry-run-test-coverage:
	poetry run poe test-coverage
