docker-build-development:
    cd .. && \
    docker build --file=api-node/Dockerfile.development --tag=ghcr.io/hongbo-miao/hm-api-node-dev:latest .

docker-push-development:
    docker push ghcr.io/hongbo-miao/hm-api-node-dev:latest

docker-run-development:
    cd .. && \
    docker run --publish=58136:58136 --name=hm-api-node --rm --env-file=api-node/.env.development.local.example.docker ghcr.io/hongbo-miao/hm-api-node-dev:latest

docker-build-production:
    cd .. && \
    docker build --file=api-node/Dockerfile --tag=ghcr.io/hongbo-miao/hm-api-node:latest .

docker-push-production:
    docker push ghcr.io/hongbo-miao/hm-api-node:latest

docker-run-production:
    cd .. && \
    docker run --publish=58136:58136 --name=hm-api-node --rm --env-file=api-node/.env.production.local.example ghcr.io/hongbo-miao/hm-api-node:latest

# Docker Compose
docker-compose-build:
    docker compose --file=docker-compose.development.yaml build
    docker compose --file=docker-compose.cypress.yaml build

docker-compose-up:
    docker compose --file=docker-compose.development.yaml up --detach
    docker compose --file=docker-compose.cypress.yaml up --detach

docker-compose-stop:
    docker compose --file=docker-compose.development.yaml stop
    docker compose --file=docker-compose.cypress.yaml stop

docker-compose-down:
    docker compose --file=docker-compose.development.yaml down --volumes
    docker compose --file=docker-compose.cypress.yaml down --volumes
