sky-launch:
    uv run sky launch experiment.sky.yaml --cluster=experiment-cluster

sky-start:
    uv run sky start experiment-cluster

sky-stop:
    uv run sky stop experiment-cluster

sky-terminate:
    uv run sky down experiment-cluster

sky-status:
    uv run sky status experiment-cluster

ssh:
    uv run ssh experiment-cluster

vscode:
    code --folder-uri=vscode-remote://ssh-remote+experiment-cluster/home/ubuntu
