# https://docs.temporal.io/docs/tctl/environment-variables

export TEMPORAL_CLI_NAMESPACE := "default"
export TEMPORAL_CLI_SHOW_STACKS := "1"

temporal--namespace-register:
    tctl --namespace=default namespace register

temporal-namespace-describe:
    tctl namespace describe

temporal-workflow-run:
    tctl workflow run --taskqueue=hello-world --workflow_type=Workflow --input='"temporal"'

temporal-workflow-start:
    tctl workflow start --taskqueue=hello-world --workflow_type=Workflow --input='"temporal"'

temporal-taskqueue-describe:
    tctl taskqueue describe --taskqueue=hello-world
