kind-up:
    kind create cluster --config=kubernetes/kind/kind-cluster.yaml

kind-down:
    kind delete cluster --name=hm-temporal

tilt-up:
    kubectl config use-context kind-hm-temporal
    tilt up

upload-recording:
    curl --request POST localhost:8085/graphql \
        --header 'content-type: application/json' \
        --data '{"query":"mutation { uploadRecording(recordingId: \"recording-2020-01-01-001\", requesterEmail: \"requester@duckcorp.io\") { workflowId } }"}'

get-recording-stage:
    curl --request POST localhost:8085/graphql \
        --header 'content-type: application/json' \
        --data '{"query":"query { recordingStage(recordingId: \"recording-2020-01-01-001\") }"}'

delete-recording:
    curl --request POST localhost:8085/graphql \
        --header 'content-type: application/json' \
        --data '{"query":"mutation { deleteRecording(recordingId: \"recording-2020-01-01-001\") { workflowId } }"}'

temporal-workflow-list:
    kubectl exec --namespace=hm-temporal deployment/temporal-admintools -- \
        temporal workflow list --namespace=recording-report

temporal-workflow-show:
    kubectl exec --namespace=hm-temporal deployment/temporal-admintools -- \
        temporal workflow show --namespace=recording-report --workflow-id=recording-report-recording-2020-01-01-001

temporal-taskqueue-describe:
    kubectl exec --namespace=hm-temporal deployment/temporal-admintools -- \
        temporal task-queue describe --namespace=recording-report --task-queue=recording-report
