POSTGRES_URL := "postgresql://admin:passw0rd@localhost:5432/hm_db?sslmode=disable&search_path=public"

migrate-up:
    migrate -database "{{ POSTGRES_URL }}" -path migrations up

migrate-down:
    migrate -database "{{ POSTGRES_URL }}" -path migrations down

migrate-force:
    migrate -database "{{ POSTGRES_URL }}" -path migrations force xxx
