install-toolchain:
    rustup install

update:
    cargo update

check:
    cargo check

dev:
    cargo run

test:
    cargo test --all-features

lint-rust-clippy:
    cargo clippy

lint-rust-clippy-fix:
    cargo clippy --fix --allow-dirty --allow-staged

lint-rust-rustfmt:
    cargo fmt --all -- --check

lint-rust-rustfmt-fix:
    cargo fmt --all

download-models:
    mkdir -p models/cohere-transcribe
    curl --silent --fail --show-error --location https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-cohere-transcribe-14-lang-int8-2026-04-01.tar.bz2 | tar --extract --bzip2 --strip-components=1 --directory models/cohere-transcribe

    mkdir -p models/silero-vad
    curl --silent --fail --show-error --location --output models/silero-vad/silero_vad.onnx https://github.com/snakers4/silero-vad/raw/v6.2.1/src/silero_vad/data/silero_vad.onnx

    mkdir -p models/zipformer
    curl --silent --fail --show-error --location https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-en-2023-06-21.tar.bz2 | tar --extract --bzip2 --strip-components=1 --directory models/zipformer
