install-toolchain:
    rustup install

update:
    cargo update

check:
    cargo check

dev:
    ENVIRONMENT=development cargo run

test:
    cargo test --all-features

lint-rust-clippy:
    cargo clippy

lint-rust-clippy-fix:
    cargo clippy --fix --allow-dirty --allow-staged

lint-rust-rustfmt:
    cargo fmt --all -- --check

lint-rust-rustfmt-fix:
    cargo fmt --all

download-ten-vad:
    mkdir -p models/ten-vad
    curl --silent --fail --show-error --location --output models/ten-vad/ten_vad.onnx https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/ten-vad.onnx

download-zipformer:
    mkdir -p models/zipformer
    curl --silent --fail --show-error --location https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-en-2023-06-21.tar.bz2 | tar --extract --bzip2 --strip-components=1 --directory models/zipformer

download-cohere-transcribe:
    mkdir -p models/cohere-transcribe
    curl --silent --fail --show-error --location https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-cohere-transcribe-14-lang-int8-2026-04-01.tar.bz2 | tar --extract --bzip2 --strip-components=1 --directory models/cohere-transcribe

download-parakeet-tdt:
    mkdir -p models/parakeet-tdt
    curl --silent --fail --show-error --location --output models/parakeet-tdt/encoder.int8.onnx https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/resolve/main/encoder.int8.onnx
    curl --silent --fail --show-error --location --output models/parakeet-tdt/decoder.int8.onnx https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/resolve/main/decoder.int8.onnx
    curl --silent --fail --show-error --location --output models/parakeet-tdt/joiner.int8.onnx https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/resolve/main/joiner.int8.onnx
    curl --silent --fail --show-error --location --output models/parakeet-tdt/tokens.txt https://huggingface.co/csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/resolve/main/tokens.txt
