argo-cd-app-create:
    argocd app create production-hm-victoria-metrics-cluster --file=argo-cd-manifests/hm-victoria-metrics-cluster-application.yaml

argo-cd-app-update:
    argocd app create production-hm-victoria-metrics-cluster --file=argo-cd-manifests/hm-victoria-metrics-cluster-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-victoria-metrics-cluster
