create:
    argocd app create production-hm-victoria-metrics-cluster --file=argo-cd-manifests/hm-victoria-metrics-cluster-application.yaml

update:
    argocd app create production-hm-victoria-metrics-cluster --file=argo-cd-manifests/hm-victoria-metrics-cluster-application.yaml --upsert

delete:
    argocd app delete production-hm-victoria-metrics-cluster
