uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

uv-run-test:
    uv run poe test

uv-run-test-coverage:
    uv run poe test-coverage

pcluster-create:
    pcluster create-cluster --cluster-name=hm-hpc-cluster --cluster-configuration=config/hm-hpc-cluster-config.yaml

pcluster-update:
    pcluster update-cluster --cluster-name=hm-hpc-cluster --cluster-configuration=config/hm-hpc-cluster-config.yaml --dryrun=true
    # Stop
    pcluster update-compute-fleet --cluster-name=hm-hpc-cluster --status=STOP_REQUESTED
    pcluster describe-compute-fleet --cluster-name=hm-hpc-cluster
    # Update
    pcluster update-cluster --cluster-name=hm-hpc-cluster --cluster-configuration=config/hm-hpc-cluster-config.yaml
    pcluster describe-cluster --cluster-name=hm-hpc-cluster
    # Start
    pcluster update-compute-fleet --cluster-name=hm-hpc-cluster --status=START_REQUESTED
    pcluster describe-compute-fleet --cluster-name=hm-hpc-cluster

pcluster-delete:
    pcluster delete-cluster --cluster-name=hm-hpc-cluster
    aws cloudformation list-stacks
    aws cloudformation delete-stack --stack-name=parallelclusternetworking-pubpriv-xxxxxxxxxxxxxx

pcluster-list:
    pcluster list-clusters

pcluster-describe:
    pcluster describe-cluster --cluster-name=hm-hpc-cluster

pcluster-ssh:
    pcluster ssh --cluster-name=hm-hpc-cluster

pcluster-dcv-connect:
    pcluster dcv-connect --cluster-name=hm-hpc-cluster
