update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python

download-sam-model:
    wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth --directory-prefix=data
