STREAM_NAME := "xxx"

install:
    # NATS server
    brew install nats-server
    # NATS Command Line Interface
    brew install nats-io/nats-tools/nats

start:
    nats-server --jetstream

stream-list:
    nats stream ls

stream-create:
    nats stream add --config="{{ STREAM_NAME }}.json"

stream-delete:
    nats stream delete "{{ STREAM_NAME }}" --force

stream-info:
    nats stream info "{{ STREAM_NAME }}"

consumer-list:
    nats consumer ls "{{ STREAM_NAME }}"

stream-subscribe:
    nats subscribe --stream="{{ STREAM_NAME }}"
