install:
    # NATS server
    brew install nats-server
    # NATS Command Line Interface
    brew tap nats-io/nats-tools
    brew install nats-io/nats-tools/nats

start:
    nats-server --jetstream

stream-list:
    nats stream ls
