seal-secrets:
    cat secrets/hm-prefect-server-secret.unsealed.yaml | \
    kubeseal \
        --controller-namespace=production-hm-sealed-secrets \
        --controller-name=hm-sealed-secrets \
        --format=yaml \
        > kubernetes-manifests/hm-prefect-server-secret.yaml
