update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

dashboard:
    uv run poe dashboard

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
