conda-create:
	conda create --name=hm-pyspark python=3.10
conda-env-remove:
	conda env remove --name=hm-pyspark
conda-activate:
	conda activate hm-pyspark
conda-deactivate:
	conda deactivate
conda-env-list:
	conda env list
conda-list-packages:
	conda list

brew-install:
	brew install openjdk@17

pip-install:
	pip install --requirement=requirements.txt

run-get-taxi-statistics:
	python taxi/get_taxi_statistics.py
run-get-taxi-statistics-sql:
	python taxi/get_taxi_statistics_sql.py
