cargo-run:
	cargo run
cargo-run-release:
	cargo run --release

lint-rust-rustfmt:
	cargo fmt --all -- --check
lint-rust-rustfmt-fix:
	cargo fmt --all
lint-rust-clippy:
	cargo clippy
lint-rust-clippy-fix:
	cargo clippy --fix --allow-dirty --allow-staged
