uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

publish-development-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=harbor.hongbomiao.com/hm/prefect-print-platform:development . && \
    docker push harbor.hongbomiao.com/hm/prefect-print-platform:development

publish-production-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=harbor.hongbomiao.com/hm/prefect-print-platform:latest . && \
    docker push harbor.hongbomiao.com/hm/prefect-print-platform:latest

deploy-development:
    uv run poe deploy --environment=development

deploy-production:
    uv run poe deploy --environment=production

run-development:
    uv run poe run -- hm-print-platform/development-hm-print-platform

run-production:
    uv run poe run -- hm-print-platform/production-hm-print-platform
