PREFECT_API_AUTH_STRING := "admin:xxx"
PREFECT_API_URL := "https://prefect.hongbomiao.com/api"

update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

# just deploy production
deploy environment:
    PREFECT_API_AUTH_STRING="{{ PREFECT_API_AUTH_STRING }}" && \
    PREFECT_API_URL="{{ PREFECT_API_URL }}" && \
    uv run poe deploy --environment={{ environment }}

# just run production
run environment:
    uv run poe run -- hm-print-platform/{{ environment }}-hm-print-platform
