uv-install-python:
    uv python install

uv-update-lock-file:
    uv lock

uv-install-dependencies:
    uv sync --dev

dev:
    uv run poe dev

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

publish-development-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=ghcr.io/hongbo-miao/hm-prefect-print-platform:development . && \
    docker push ghcr.io/hongbo-miao/hm-prefect-print-platform:development

publish-production-docker-image:
    docker build --platform=linux/amd64 --file=Dockerfile --tag=ghcr.io/hongbo-miao/hm-prefect-print-platform:latest . && \
    docker push ghcr.io/hongbo-miao/hm-prefect-print-platform:latest

deploy-development:
    uv run poe deploy --environment=development

deploy-production:
    uv run poe deploy --environment=production

run-development:
    uv run poe run -- print-platform/hm-development-print-platform

run-production:
    uv run poe run -- print-platform/hm-production-print-platform
