/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FireRouteImport } from './routes/fire'
import { Route as IndexRouteImport } from './routes/index'

const FireRoute = FireRouteImport.update({
  id: '/fire',
  path: '/fire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fire': typeof FireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fire': typeof FireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fire': typeof FireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fire'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fire'
  id: '__root__' | '/' | '/fire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FireRoute: typeof FireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fire': {
      id: '/fire'
      path: '/fire'
      fullPath: '/fire'
      preLoaderRoute: typeof FireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FireRoute: FireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
