PRODUCTION_DOCKER_IMAGE_TAG := "ghcr.io/hongbo-miao/hm-api-python:latest"

update-lock-file:
    uv lock

install-dependencies:
    brew install librdkafka
    export C_INCLUDE_PATH=/opt/homebrew/include
    export LIBRARY_PATH=/opt/homebrew/lib
    uv sync --dev

dev:
    uv run poe dev

serve:
    uv run poe serve

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

docker-build:
    cd .. && \
    docker build --file=api-python/Dockerfile --tag="{{ PRODUCTION_DOCKER_IMAGE_TAG }}" .

docker-push:
    docker push "{{ PRODUCTION_DOCKER_IMAGE_TAG }}"

docker-run:
    docker run --publish=35903:35903 --name=hm-api-python --rm "{{ PRODUCTION_DOCKER_IMAGE_TAG }}"
