---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hm-falcosidekick-secret
  namespace: production-hm-falcosidekick
spec:
  encryptedData:
    FALCOSIDEKICK_UI_USER: AgCgo4ZnUmzasZONTQMDTh0MTPkbanz+a9usSdH6kkU8eMVS9Qtbcs4Z+M81D0/XzrRPNQE+/Mm+RbYC9vbPFUfB2HI/KlZw0in+XM+DNY/p9wRHip8s70pN6ihx5fClbbeI/x5YRSuu+bgxCynpsMrqcMeapzwQQjnVqTEaLhOxdr+FKe1HFdDnOkVTfJJvb0e9Mbz599fsRxphw45z/NoodtrXPauCbRs3OMcSFzQL6Yn7PH5qN/a2cDT62Je+WKpv1vLebbg5WrfaWs2pBM6YVtEhoBvWWFmanHD1abLprGxeUT+gXefpzJ98sxp1oRxr9j8rwOht+m8QlXpJ0uxYdbQ6mEeRESy/uEF3E7D2hEJpnsDfE2S/jbWrXgcg0OkiBSFaVi1Skv9KEHX+f0wdHwTIWEuy7iDkRwXnV4DkJ9ga2V3jzbcqsFoLN3LcLsdBYVENdE6XFcyRkhg7ByXLISnV6nfkPW35EmjjYy2EcXe707ysbKqygc/evLst1uZ8kJU2M6A2oHcQKsO1gg4vzWtgwwjYebKOiz1HvXQr8UbLmYeDzlNfNXR7RFI9xVlAYKJylov+3/ITNO30f6dKzNmj0rwKRTRZ3c2gMSN5Q7c/QxuitQ53Ka2luHjcMpisPGyPIOXy4+bzqtBvIo8BESxI6ujk2ucn2l79g5445RDb9GArIAiD0E5vD/CylnCsV4UE/STA0vlw2FzDoyP9PbdS8ZKFbf72LUPZhHTjU78e/XdtO1r1itiDvCUTbMXuv3YixdyA+OndxMkL67XHiKLf4gbes0QrLB+x2hM=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: falcosidekick
        app.kubernetes.io/part-of: production-hm-falcosidekick
      name: hm-falcosidekick-secret
      namespace: production-hm-falcosidekick
