update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run poe dev -- model=small activation=gelu optimizer=sgd epoch_count=5

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage
