argo-cd-app-create:
    argocd app create production-hm-skypilot --file=argo-cd-manifests/hm-skypilot-application.yaml

argo-cd-app-update:
    argocd app create production-hm-skypilot --file=argo-cd-manifests/hm-skypilot-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-skypilot --yes
