argo-cd-app-create:
    argocd app create production-hm-skypilot --file=argo-cd-manifests/hm-skypilot-application.yaml

argo-cd-app-update:
    argocd app create production-hm-skypilot --file=argo-cd-manifests/hm-skypilot-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-skypilot --yes

sealed-secrets-seal-hm-skypilot-secret:
    cat secrets/hm-skypilot-secret.unsealed.yaml | \
    kubeseal \
    	--controller-namespace=production-hm-sealed-secrets \
    	--controller-name=hm-sealed-secrets \
    	--format=yaml \
    	> manifests/hm-skypilot-secret.yaml

sealed-secrets-seal-runpod-secret:
    cat secrets/runpod-secret.unsealed.yaml | \
    kubeseal \
    	--controller-namespace=production-hm-sealed-secrets \
    	--controller-name=hm-sealed-secrets \
    	--format=yaml \
    	> manifests/runpod-secret.yaml
