update-lock-file:
    uv lock

install-dependencies:
    uv sync --dev

dev:
    uv run deepspeed --include localhost:0,1 src/main.py

test:
    uv run poe test

test-coverage:
    uv run poe test-coverage

static-type-check-python:
    uv run poe static-type-check-python
