argo-cd-app-create:
	argocd app create hm-external-dns --file=argo-cd-manifests/hm-external-dns.yaml
argo-cd-app-update:
	argocd app create hm-external-dns --file=argo-cd-manifests/hm-external-dns.yaml --upsert
