initialize:
    # vagrant init ubuntu/jammy64
    vagrant init bento/ubuntu-22.04-arm64

up:
    vagrant up --provider=parallels

suspend:
    vagrant suspend

halt:
    vagrant halt

destroy:
    vagrant destroy --force

ssh:
    vagrant ssh

status:
    vagrant status
