# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-22.04-arm64'
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'playbook.yml'
  end
end
