---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: stream-ai-inference
spec:
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ollama
  namespace: stream-ai-inference
  labels:
    kubernetes.io/service-name: ollama
addressType: IPv4
endpoints:
  - addresses:
      - HOST_OLLAMA_ADDRESS
    conditions:
      ready: true
ports:
  - name: http
    port: 11434
    protocol: TCP
