---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hm-spark-connect-server-large-service-account
  namespace: production-hm-spark-connect-server-large
  labels:
    app.kubernetes.io/name: spark-connect-server-large
    app.kubernetes.io/part-of: production-hm-spark-connect-server-large
