argo-cd-app-create:
    argocd app create production-hm-goldilocks --file=argo-cd-manifests/hm-goldilocks-application.yaml

argo-cd-app-update:
    argocd app create production-hm-goldilocks --file=argo-cd-manifests/hm-goldilocks-application.yaml --upsert

argo-cd-app-delete:
    argocd app delete production-hm-goldilocks --yes
