poetry-env-use:
	poetry env use python3.11
poetry-update-lock-file:
	poetry lock --no-update
poetry-install:
	poetry install

poetry-run-deploy:
	poetry run poe deploy
poetry-run-undeploy:
	poetry run poe undeploy
poetry-run-test:
	poetry run poe test
poetry-run-test-coverage:
	poetry run poe test-coverage
