argo-cd-app-create:
	argocd app create hm-metrics-server --file=argo-cd-manifests/hm-metrics-server.yaml
argo-cd-app-update:
	argocd app create hm-metrics-server --file=argo-cd-manifests/hm-metrics-server.yaml --upsert
