create:
    argocd app create production-hm-netdata --file=argo-cd-manifests/hm-netdata-application.yaml

update:
    argocd app create production-hm-netdata --file=argo-cd-manifests/hm-netdata-application.yaml --upsert

delete:
    argocd app delete production-hm-netdata --yes
