---
name: . Test Operating System

'on':
  workflow_call:
    inputs:
      # Workflows
      workflow:
        required: true
        type: boolean
      # Applications
      windows-calculator:
        required: true
        type: boolean

jobs:
  windows-calculator-test:
    name: Windows (calculator) | Test
    if: ${{ inputs.workflow || inputs.windows-calculator }}
    runs-on: windows-2025
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          cache: true
          rust-src-dir: operating-system/windows/calculator
      - name: Install dependencies
        working-directory: operating-system/windows/calculator
        run: |
          cargo build --locked
      - name: Test
        working-directory: operating-system/windows/calculator
        run: |
          cargo test --all-features
