name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  # https://github.com/marketplace/actions/deploy-to-heroku
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hongbomiao"
          heroku_email: "hongbo.miao@outlook.com"
