name: Docker

on:
  push:
    branches: [ main ]

jobs:
  push:
    name: Push to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.api.production
          push: true
          tags: hongbomiao/hongbomiao-api:latest
      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
