devices:
({
  type = "soapysdr";
  device_string = "driver=airspy";
  gain = 21;
  centerfreq = 123000000;
  sample_rate = 10000000;
  channels:
  (
    {
      // KSJC ATIS - looped voice, always transmitting
      freq = 126950000;
      modulation = "am";
      label = "ksjc-atis";
      squelch_threshold = -65;
      outputs:
      ({
        type = "icecast";
        server = "localhost";
        port = 8000;
        mountpoint = "ksjc-atis.mp3";
        name = "KSJC ATIS";
        genre = "Aviation";
        username = "source";
        password = "passw0rd";
      });
    },
    {
      // KSJC Ground - push-to-talk
      freq = 121700000;
      modulation = "am";
      label = "ksjc-ground";
      squelch_threshold = -64;
      outputs:
      ({
        type = "icecast";
        server = "localhost";
        port = 8000;
        mountpoint = "ksjc-ground.mp3";
        name = "KSJC Ground";
        genre = "Aviation";
        username = "source";
        password = "passw0rd";
      });
    },
    {
      // KSJC Tower - push-to-talk
      freq = 124000000;
      modulation = "am";
      label = "ksjc-tower";
      squelch_threshold = -64;
      outputs:
      ({
        type = "icecast";
        server = "localhost";
        port = 8000;
        mountpoint = "ksjc-tower.mp3";
        name = "KSJC Tower";
        genre = "Aviation";
        username = "source";
        password = "passw0rd";
      });
    }
  );
});
