# Host (macOS)
ssh:
	ssh hongbo-miao@10.211.55.39

# Windows
show-process:
	Get-Process
show-service:
	Get-Service
show-history:
	Get-History
show-connection:
	netstat
show-current-user:
	whoami
show-command-location:
	where.exe xxx

show-powershell-version:
	$PSVersionTable.PSVersion

execution-policy-get:
	Get-ExecutionPolicy
execution-policy-set:
	Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
